import type { Transformation, TransformationCategory, TransformationSubcategory, Gender } from '@/types';

export const CATEGORIES: Record<TransformationCategory, {
  name: string;
  maleName?: string;
  icon: string;
  maleIcon?: string;
  description: string;
}> = {
  hairstyles: {
    name: 'Hairstyles',
    icon: '✂️',
    description: 'Change hair color, style, and length',
  },
  makeup: {
    name: 'Makeup',
    maleName: 'Grooming',
    icon: '💄',
    maleIcon: '🪒',
    description: 'Apply lipstick, eye makeup, and full looks',
  },
  clothing: {
    name: 'Clothing & Style',
    icon: '👔',
    description: 'Try on formal, casual, cultural, and decade-inspired outfits',
  },
  facial: {
    name: 'Facial Features',
    icon: '✨',
    description: 'Refine nose, jawline, eyes, lips, and cheekbones',
  },
  body: {
    name: 'Body & Shape',
    icon: '💪',
    description: 'Transform body shape and proportions',
  },
  'age-fantasy': {
    name: 'Age & Fantasy',
    icon: '🎭',
    description: 'Age transformations and fantasy character styles',
  },
};

export const SUBCATEGORIES: Record<TransformationCategory, TransformationSubcategory[]> = {
  hairstyles: [
    { id: 'color', name: 'Color', icon: '🎨' },
    { id: 'style', name: 'Style', icon: '💇' },
    { id: 'length', name: 'Length', icon: '📏' },
    { id: 'facial-hair', name: 'Facial Hair', icon: '🧔', gender: 'male' },
  ],
  makeup: [
    { id: 'lips', name: 'Lips', icon: '💋', gender: 'female' },
    { id: 'eyes', name: 'Eyes', icon: '👁️', gender: 'female' },
    { id: 'face', name: 'Face', icon: '🧖', gender: 'female' },
    { id: 'full-looks', name: 'Full Looks', icon: '🪄' },
    { id: 'skin', name: 'Skin', icon: '✨', gender: 'male' },
    { id: 'brows', name: 'Brows', icon: '🫤', gender: 'male' },
  ],
  clothing: [
    { id: 'formal', name: 'Formal', icon: '🤵' },
    { id: 'casual', name: 'Casual', icon: '👕' },
    { id: 'cultural', name: 'Cultural', icon: '🌍' },
    { id: 'decades', name: 'Decades', icon: '⏳' },
  ],
  facial: [
    { id: 'nose', name: 'Nose', icon: '👃' },
    { id: 'jawline', name: 'Jawline', icon: '🗣️' },
    { id: 'eyes', name: 'Eyes', icon: '👀' },
    { id: 'lips', name: 'Lips', icon: '👄' },
    { id: 'cheekbones', name: 'Cheekbones', icon: '😘' },
  ],
  body: [
    { id: 'body', name: 'Body', icon: '🧑' },
  ],
  'age-fantasy': [
    { id: 'age', name: 'Age', icon: '⌛' },
    { id: 'fantasy', name: 'Fantasy', icon: '🧙' },
  ],
};

export const TRANSFORMATIONS: Transformation[] = [
  // ============================================================
  // HAIRSTYLES - Color (14 items) — all neutral
  // ============================================================
  {
    id: 'hair-color-blonde',
    name: 'Blonde',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to golden blonde while keeping everything else the same",
    icon: '👱',
    intensity: 0.65,
  },
  {
    id: 'hair-color-brunette',
    name: 'Brunette',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to rich brunette brown while keeping everything else the same",
    icon: '👩',
    intensity: 0.65,
  },
  {
    id: 'hair-color-red-auburn',
    name: 'Red/Auburn',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to red auburn while keeping everything else the same",
    icon: '🦰',
    intensity: 0.65,
  },
  {
    id: 'hair-color-black',
    name: 'Black',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to jet black while keeping everything else the same",
    icon: '🖤',
    intensity: 0.65,
  },
  {
    id: 'hair-color-platinum',
    name: 'Platinum',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to platinum white blonde while keeping everything else the same",
    icon: '⭐',
    intensity: 0.65,
  },
  {
    id: 'hair-color-silver-gray',
    name: 'Silver/Gray',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to silver gray while keeping everything else the same",
    icon: '🤍',
    intensity: 0.65,
  },
  {
    id: 'hair-color-pink',
    name: 'Pink',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to bright pink while keeping everything else the same",
    icon: '🌸',
    intensity: 0.65,
  },
  {
    id: 'hair-color-blue',
    name: 'Blue',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to vibrant blue while keeping everything else the same",
    icon: '💙',
    intensity: 0.65,
  },
  {
    id: 'hair-color-purple',
    name: 'Purple',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to deep purple while keeping everything else the same",
    icon: '💜',
    intensity: 0.65,
  },
  {
    id: 'hair-color-green',
    name: 'Green',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to emerald green while keeping everything else the same",
    icon: '💚',
    intensity: 0.65,
  },
  {
    id: 'hair-color-ombre',
    name: 'Ombre',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair to an ombre style, dark roots transitioning to light blonde tips",
    icon: '🌅',
    intensity: 0.65,
  },
  {
    id: 'hair-color-highlights',
    name: 'Highlights',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Add sun-kissed blonde highlights throughout the person's hair",
    icon: '☀️',
    intensity: 0.65,
  },
  {
    id: 'hair-color-balayage',
    name: 'Balayage',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: 'Give the person a beautiful balayage hair coloring with natural-looking hand-painted highlights',
    icon: '🌟',
    intensity: 0.65,
  },
  {
    id: 'hair-color-rainbow',
    name: 'Rainbow',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair to rainbow colors with streaks of red, orange, yellow, green, blue, and purple",
    icon: '🌈',
    intensity: 0.65,
  },

  // ============================================================
  // HAIRSTYLES - Style — neutral
  // ============================================================
  {
    id: 'hair-style-long-waves',
    name: 'Long Waves',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to long flowing wavy hair",
    icon: '🌊',
    intensity: 0.70,
  },
  {
    id: 'hair-style-curly',
    name: 'Curly',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to beautiful natural curly hair",
    icon: '➰',
    intensity: 0.70,
  },
  {
    id: 'hair-style-straight',
    name: 'Straight',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to sleek straight hair",
    icon: '✒️',
    intensity: 0.70,
  },
  {
    id: 'hair-style-braids',
    name: 'Braids',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to elegant braided hair",
    icon: '🧶',
    intensity: 0.70,
  },
  {
    id: 'hair-style-mohawk',
    name: 'Mohawk',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a bold mohawk",
    icon: '🤘',
    intensity: 0.70,
  },
  {
    id: 'hair-style-afro',
    name: 'Afro',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a full natural afro",
    icon: '🦱',
    intensity: 0.70,
  },
  {
    id: 'hair-style-locs',
    name: 'Locs',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to dreadlocks",
    icon: '🧵',
    intensity: 0.70,
  },
  {
    id: 'hair-style-box-braids',
    name: 'Box Braids',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to box braids",
    icon: '💫',
    intensity: 0.70,
  },
  {
    id: 'hair-style-mullet',
    name: 'Mullet',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a modern mullet",
    icon: '🎸',
    intensity: 0.70,
  },
  {
    id: 'hair-style-shag',
    name: 'Shag',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a layered shag cut",
    icon: '🌿',
    intensity: 0.70,
  },
  {
    id: 'hair-style-wolf-cut',
    name: 'Wolf Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a trendy wolf cut with choppy layers",
    icon: '🐺',
    intensity: 0.70,
  },

  // ============================================================
  // HAIRSTYLES - Style — female
  // ============================================================
  {
    id: 'hair-style-bob',
    name: 'Bob',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a classic chin-length bob cut",
    icon: '💇',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-pixie',
    name: 'Pixie Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a short pixie cut",
    icon: '🧕',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-ponytail',
    name: 'Ponytail',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a high ponytail",
    icon: '🎀',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-messy-bun',
    name: 'Messy Bun',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a casual messy bun",
    icon: '🧷',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-bangs',
    name: 'Bangs',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Add blunt bangs to the person's hairstyle while keeping the rest the same",
    icon: '😎',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-french-twist',
    name: 'French Twist',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to an elegant French twist updo",
    icon: '🌀',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-side-swept',
    name: 'Side Swept',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a glamorous side-swept style",
    icon: '💨',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-half-up',
    name: 'Half Up Half Down',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a half up half down style",
    icon: '⬆️',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-space-buns',
    name: 'Space Buns',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to playful space buns",
    icon: '🪐',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-curtain-bangs',
    name: 'Curtain Bangs',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Add curtain bangs to the person's hairstyle framing the face",
    icon: '🪟',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-layered',
    name: 'Layered',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a layered cut with face-framing layers",
    icon: '🍃',
    intensity: 0.70,
    gender: 'female',
  },

  // ============================================================
  // HAIRSTYLES - Style — male
  // ============================================================
  {
    id: 'hair-style-buzz-cut',
    name: 'Buzz Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a very short buzz cut",
    icon: '👨‍🦲',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-undercut',
    name: 'Undercut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a trendy undercut with longer hair on top",
    icon: '✂️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-fade',
    name: 'Fade',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a clean fade haircut",
    icon: '💈',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-crew-cut',
    name: 'Crew Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a classic crew cut",
    icon: '🪖',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-slick-back',
    name: 'Slick Back',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a slicked back style",
    icon: '🕴️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-man-bun',
    name: 'Man Bun',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a man bun",
    icon: '🔝',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-pompadour',
    name: 'Pompadour',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a classic pompadour",
    icon: '🎵',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-quiff',
    name: 'Quiff',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a modern quiff",
    icon: '🔼',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-comb-over',
    name: 'Comb Over',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a side-parted comb over",
    icon: '➡️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-flat-top',
    name: 'Flat Top',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a flat top",
    icon: '⬛',
    intensity: 0.70,
    gender: 'male',
  },

  // ============================================================
  // HAIRSTYLES - Facial Hair (male only)
  // ============================================================
  {
    id: 'hair-facial-full-beard',
    name: 'Full Beard',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a full thick beard',
    icon: '🧔',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-stubble',
    name: 'Stubble',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person light stubble facial hair',
    icon: '🌫️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-goatee',
    name: 'Goatee',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a goatee beard on the chin',
    icon: '🎯',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-mustache',
    name: 'Mustache',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a classic mustache',
    icon: '🥸',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-handlebar',
    name: 'Handlebar Mustache',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a handlebar mustache with curled ends',
    icon: '〰️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-van-dyke',
    name: 'Van Dyke',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a Van Dyke beard with mustache and pointed chin beard',
    icon: '🎭',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-mutton-chops',
    name: 'Mutton Chops',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person mutton chop sideburns',
    icon: '🐑',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-soul-patch',
    name: 'Soul Patch',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a small soul patch below the lower lip',
    icon: '▪️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-clean-shaven',
    name: 'Clean Shaven',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Make the person completely clean shaven with no facial hair',
    icon: '✨',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-five-oclock',
    name: "5 O'Clock Shadow",
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: "Give the person a 5 o'clock shadow with slight stubble",
    icon: '🕐',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-lumberjack',
    name: 'Lumberjack Beard',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a big rugged lumberjack beard',
    icon: '🪓',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-chinstrap',
    name: 'Chinstrap',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a thin chinstrap beard along the jawline',
    icon: '⛓️',
    intensity: 0.70,
    gender: 'male',
  },

  // ============================================================
  // HAIRSTYLES - Length (5 items) — all neutral
  // ============================================================
  {
    id: 'hair-length-very-short',
    name: 'Very Short/Crop',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to a very short cropped style",
    icon: '✂️',
    intensity: 0.70,
  },
  {
    id: 'hair-length-short',
    name: 'Short',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to a short above-the-ears length",
    icon: '👈',
    intensity: 0.70,
  },
  {
    id: 'hair-length-medium',
    name: 'Medium',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to a medium shoulder-length",
    icon: '↔️',
    intensity: 0.70,
  },
  {
    id: 'hair-length-long',
    name: 'Long',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to long hair reaching the middle of the back",
    icon: '⬇️',
    intensity: 0.70,
  },
  {
    id: 'hair-length-very-long',
    name: 'Very Long',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to very long flowing hair reaching the waist",
    icon: '🧜',
    intensity: 0.70,
  },

  // ============================================================
  // MAKEUP - Lips (7 items) — all female
  // ============================================================
  {
    id: 'makeup-lips-red',
    name: 'Red Lipstick',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply classic red lipstick to the person',
    icon: '💄',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-nude',
    name: 'Nude Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply natural nude lipstick to the person',
    icon: '🤎',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-pink',
    name: 'Pink Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply soft pink lipstick to the person',
    icon: '🌸',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-bold-berry',
    name: 'Bold Berry',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply bold berry-colored lipstick to the person',
    icon: '🍇',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-glossy',
    name: 'Glossy Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: "Apply shiny glossy lip gloss to the person's lips",
    icon: '✨',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-matte-dark',
    name: 'Matte Dark',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply dark matte burgundy lipstick to the person',
    icon: '🖤',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-ombre',
    name: 'Ombre Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply ombre lip color to the person, darker on the outside fading to lighter in the center',
    icon: '🌅',
    intensity: 0.60,
    gender: 'female',
  },

  // ============================================================
  // MAKEUP - Eyes (6 items) — all female
  // ============================================================
  {
    id: 'makeup-eyes-smokey',
    name: 'Smokey Eye',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply dramatic smokey eye makeup with dark eyeshadow and blended edges to the person',
    icon: '🌫️',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-cat-eye',
    name: 'Cat Eye',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply cat eye winged eyeliner makeup to the person',
    icon: '🐱',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-natural',
    name: 'Natural Eyes',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply subtle natural eye makeup with light eyeshadow and thin eyeliner to the person',
    icon: '🌿',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-glitter',
    name: 'Glitter Eyes',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply sparkly glitter eyeshadow makeup to the person',
    icon: '🌟',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-dramatic-lashes',
    name: 'Dramatic Lashes',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply dramatic long false eyelashes to the person',
    icon: '🫶',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-colored-contacts',
    name: 'Colored Contacts',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to bright blue",
    icon: '🔵',
    intensity: 0.60,
    gender: 'female',
  },

  // ============================================================
  // MAKEUP - Face (5 items) — all female
  // ============================================================
  {
    id: 'makeup-face-clear-skin',
    name: 'Clear Skin',
    category: 'makeup',
    subcategory: 'face',
    prompt: 'Remove all makeup and give the person clear, natural, glowing skin',
    icon: '✨',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-face-contoured',
    name: 'Contoured',
    category: 'makeup',
    subcategory: 'face',
    prompt: "Apply professional contouring makeup to the person's face, defining cheekbones and jawline",
    icon: '💎',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-face-bronzed-glow',
    name: 'Bronzed Glow',
    category: 'makeup',
    subcategory: 'face',
    prompt: 'Apply bronzer and highlighter to give the person a sun-kissed golden glow',
    icon: '☀️',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-face-dewy-skin',
    name: 'Dewy Skin',
    category: 'makeup',
    subcategory: 'face',
    prompt: 'Give the person dewy, glass-like skin with a luminous healthy glow',
    icon: '💧',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-face-freckles',
    name: 'Freckles',
    category: 'makeup',
    subcategory: 'face',
    prompt: "Add cute natural-looking freckles across the person's nose and cheeks",
    icon: '🤎',
    intensity: 0.60,
    gender: 'female',
  },

  // ============================================================
  // MAKEUP - Full Looks (8 items) — female
  // ============================================================
  {
    id: 'makeup-full-natural-glam',
    name: 'Natural Glam',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply natural glamour makeup with subtle eyeshadow, mascara, light blush, and nude lip',
    icon: '🌟',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-red-carpet',
    name: 'Red Carpet',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply full red carpet glamour makeup with smokey eyes, contoured face, and bold red lips',
    icon: '🏆',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-gothic',
    name: 'Gothic',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply gothic dark makeup with black eyeshadow, dark lipstick, and pale foundation',
    icon: '🦇',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-90s-supermodel',
    name: '90s Supermodel',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply 90s supermodel makeup with brown lip liner, matte lips, and defined brows',
    icon: '👠',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-avant-garde',
    name: 'Avant-Garde',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply artistic avant-garde makeup with bold colors and creative designs',
    icon: '🎨',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-k-beauty',
    name: 'K-Beauty',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply Korean beauty makeup style with gradient lips, subtle blush, and dewy skin',
    icon: '🌸',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-editorial',
    name: 'Editorial',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply high fashion editorial makeup with bold artistic elements',
    icon: '📷',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-bridal',
    name: 'Bridal',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply beautiful bridal wedding makeup with soft romantic tones and glowing skin',
    icon: '👰',
    intensity: 0.60,
    gender: 'female',
  },

  // ============================================================
  // GROOMING - Skin (male)
  // ============================================================
  {
    id: 'grooming-skin-clear',
    name: 'Clear Skin',
    category: 'makeup',
    subcategory: 'skin',
    prompt: 'Give the person clear blemish-free skin with a natural healthy look',
    icon: '✨',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-skin-bronzed',
    name: 'Bronzed',
    category: 'makeup',
    subcategory: 'skin',
    prompt: 'Give the person a sun-kissed bronzed skin tone',
    icon: '☀️',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-skin-matte',
    name: 'Matte Skin',
    category: 'makeup',
    subcategory: 'skin',
    prompt: 'Give the person smooth matte skin with no shine',
    icon: '🪨',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-skin-healthy-glow',
    name: 'Healthy Glow',
    category: 'makeup',
    subcategory: 'skin',
    prompt: 'Give the person healthy glowing skin with a natural radiance',
    icon: '💡',
    intensity: 0.60,
    gender: 'male',
  },

  // ============================================================
  // GROOMING - Brows (male)
  // ============================================================
  {
    id: 'grooming-brows-thick',
    name: 'Thick Brows',
    category: 'makeup',
    subcategory: 'brows',
    prompt: 'Give the person thick bold eyebrows',
    icon: '🟫',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-brows-groomed',
    name: 'Groomed Brows',
    category: 'makeup',
    subcategory: 'brows',
    prompt: 'Give the person neatly groomed and shaped eyebrows',
    icon: '✂️',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-brows-bushy',
    name: 'Bushy Brows',
    category: 'makeup',
    subcategory: 'brows',
    prompt: 'Give the person natural bushy eyebrows',
    icon: '🌿',
    intensity: 0.60,
    gender: 'male',
  },

  // ============================================================
  // GROOMING - Full Looks (male)
  // ============================================================
  {
    id: 'grooming-full-well-groomed',
    name: 'Well-Groomed',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Give the person a polished well-groomed look with clean skin and neat facial hair',
    icon: '👔',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-full-rugged',
    name: 'Rugged',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Give the person a rugged masculine look with textured skin and slight stubble',
    icon: '🏔️',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-full-pretty-boy',
    name: 'Pretty Boy',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Give the person a refined pretty boy look with flawless skin and defined features',
    icon: '💎',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-full-distinguished',
    name: 'Distinguished',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Give the person a distinguished mature look with subtle gray at the temples and refined features',
    icon: '🎩',
    intensity: 0.60,
    gender: 'male',
  },

  // ============================================================
  // CLOTHING - Formal
  // ============================================================
  {
    id: 'clothing-formal-business-suit',
    name: 'Business Suit',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a tailored professional business suit",
    icon: '💼',
    intensity: 0.75,
  },
  {
    id: 'clothing-formal-tuxedo',
    name: 'Tuxedo',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with an elegant black tuxedo with bow tie",
    icon: '🤵',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-formal-three-piece',
    name: 'Three-Piece Suit',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a classic three-piece suit with vest",
    icon: '🤵',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-formal-military',
    name: 'Military Dress',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a formal military dress uniform",
    icon: '🎖️',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-formal-evening-gown',
    name: 'Evening Gown',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a stunning floor-length evening gown",
    icon: '👗',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-formal-cocktail-dress',
    name: 'Cocktail Dress',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a stylish cocktail dress",
    icon: '🍸',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-formal-ball-gown',
    name: 'Ball Gown',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a grand ball gown with flowing skirt",
    icon: '👸',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-formal-jumpsuit',
    name: 'Jumpsuit',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a sleek tailored jumpsuit",
    icon: '🦸‍♀️',
    intensity: 0.75,
    gender: 'female',
  },

  // ============================================================
  // CLOTHING - Casual
  // ============================================================
  {
    id: 'clothing-casual-streetwear',
    name: 'Streetwear',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with trendy urban streetwear",
    icon: '👟',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-athleisure',
    name: 'Athleisure',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with stylish athletic athleisure wear",
    icon: '🏃',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-bohemian',
    name: 'Bohemian',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a bohemian flowing outfit with natural fabrics",
    icon: '🌻',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-preppy',
    name: 'Preppy',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a preppy outfit with polo shirt and clean lines",
    icon: '🏌️',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-minimalist',
    name: 'Minimalist',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a minimalist modern outfit in neutral tones",
    icon: '▫️',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-workwear',
    name: 'Workwear',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with rugged workwear with boots and denim",
    icon: '🔧',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-casual-biker',
    name: 'Biker',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a leather biker jacket and boots",
    icon: '🏍️',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-casual-cottagecore',
    name: 'Cottagecore',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a cottagecore outfit with floral dress and natural fabrics",
    icon: '🌸',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-casual-y2k-girly',
    name: 'Y2K Girly',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with Y2K girly fashion with low-rise and baby tees",
    icon: '💖',
    intensity: 0.75,
    gender: 'female',
  },

  // ============================================================
  // CLOTHING - Cultural (4 items) — all neutral
  // ============================================================
  {
    id: 'clothing-cultural-kimono',
    name: 'Kimono',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with a beautiful traditional Japanese kimono",
    icon: '🎌',
    intensity: 0.75,
  },
  {
    id: 'clothing-cultural-sari',
    name: 'Sari',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with an elegant traditional Indian sari",
    icon: '🤎',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-cultural-hanbok',
    name: 'Hanbok',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with a traditional Korean hanbok",
    icon: '🇰🇷',
    intensity: 0.75,
  },
  {
    id: 'clothing-cultural-scottish-highland',
    name: 'Scottish Highland',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with traditional Scottish highland dress with tartan kilt",
    icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    intensity: 0.75,
  },

  // ============================================================
  // CLOTHING - Decades (7 items) — all neutral
  // ============================================================
  {
    id: 'clothing-decades-1950s',
    name: '1950s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1950s retro fashion",
    icon: '🕺',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1960s',
    name: '1960s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1960s mod fashion",
    icon: '☮️',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1970s',
    name: '1970s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1970s disco fashion",
    icon: '🕺',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1980s',
    name: '1980s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1980s power fashion with bold colors and shoulder pads",
    icon: '🎙️',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1990s',
    name: '1990s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1990s grunge fashion",
    icon: '🎸',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-y2k',
    name: 'Y2K',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with Y2K fashion style",
    icon: '💿',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-futuristic',
    name: 'Futuristic',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with futuristic sci-fi fashion",
    icon: '🚀',
    intensity: 0.75,
  },

  // ============================================================
  // FACIAL - Nose (4 items) — all neutral
  // ============================================================
  {
    id: 'facial-nose-smaller',
    name: 'Smaller',
    category: 'facial',
    subcategory: 'nose',
    prompt: "Make the person's nose slightly smaller and more refined while keeping their identity",
    icon: '👃',
    intensity: 0.55,
  },
  {
    id: 'facial-nose-button',
    name: 'Button Nose',
    category: 'facial',
    subcategory: 'nose',
    prompt: 'Give the person a small, round, slightly upturned nose with a soft rounded tip while keeping everything else the same',
    icon: '🔘',
    intensity: 0.55,
  },
  {
    id: 'facial-nose-straight-bridge',
    name: 'Straight Bridge',
    category: 'facial',
    subcategory: 'nose',
    prompt: 'Give the person a straight nose bridge while keeping everything else the same',
    icon: '➖',
    intensity: 0.55,
  },
  {
    id: 'facial-nose-wider',
    name: 'Wider',
    category: 'facial',
    subcategory: 'nose',
    prompt: "Make the person's nose slightly wider while keeping everything else the same",
    icon: '↔️',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Jawline (4 items) — all neutral
  // ============================================================
  {
    id: 'facial-jawline-chiseled',
    name: 'Chiseled',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a sharper more chiseled jawline while keeping everything else the same',
    icon: '💠',
    intensity: 0.55,
  },
  {
    id: 'facial-jawline-softer',
    name: 'Softer',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a softer more rounded jawline while keeping everything else the same',
    icon: '⭕',
    intensity: 0.55,
  },
  {
    id: 'facial-jawline-square',
    name: 'Square',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a strong square jawline while keeping everything else the same',
    icon: '◾',
    intensity: 0.55,
  },
  {
    id: 'facial-jawline-v-shape',
    name: 'V-Shape',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a V-shaped jawline while keeping everything else the same',
    icon: '✔️',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Eyes (4 items) — all neutral
  // ============================================================
  {
    id: 'facial-eyes-larger',
    name: 'Larger Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Make the person's eyes slightly larger and more prominent",
    icon: '👀',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-almond',
    name: 'Almond Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: 'Give the person more almond-shaped eyes',
    icon: '🌰',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-rounder',
    name: 'Rounder Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: 'Give the person rounder more open eyes',
    icon: '⚪',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-green',
    name: 'Green Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to vivid green",
    icon: '🟢',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-blue',
    name: 'Blue Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to bright blue",
    icon: '🔵',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-brown',
    name: 'Brown Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to warm brown",
    icon: '🟤',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-hazel',
    name: 'Hazel Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to hazel with golden-brown tones",
    icon: '🟡',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Lips (4 items) — all neutral
  // ============================================================
  {
    id: 'facial-lips-fuller',
    name: 'Fuller Lips',
    category: 'facial',
    subcategory: 'lips',
    prompt: 'Give the person fuller plumper lips while keeping everything else the same',
    icon: '👄',
    intensity: 0.55,
  },
  {
    id: 'facial-lips-thinner',
    name: 'Thinner Lips',
    category: 'facial',
    subcategory: 'lips',
    prompt: 'Give the person thinner more refined lips while keeping everything else the same',
    icon: '➖',
    intensity: 0.55,
  },
  {
    id: 'facial-lips-wider-smile',
    name: 'Wider Smile',
    category: 'facial',
    subcategory: 'lips',
    prompt: 'Give the person a wider more prominent smile',
    icon: '😁',
    intensity: 0.55,
  },
  {
    id: 'facial-lips-cupids-bow',
    name: "Cupid's Bow",
    category: 'facial',
    subcategory: 'lips',
    prompt: "Give the person more defined cupid's bow lips",
    icon: '🏹',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Cheekbones (3 items) — all neutral
  // ============================================================
  {
    id: 'facial-cheekbones-higher',
    name: 'Higher',
    category: 'facial',
    subcategory: 'cheekbones',
    prompt: 'Give the person higher more prominent cheekbones',
    icon: '⬆️',
    intensity: 0.55,
  },
  {
    id: 'facial-cheekbones-more-prominent',
    name: 'More Prominent',
    category: 'facial',
    subcategory: 'cheekbones',
    prompt: "Make the person's cheekbones more defined and sculpted",
    icon: '💎',
    intensity: 0.55,
  },
  {
    id: 'facial-cheekbones-softer',
    name: 'Softer',
    category: 'facial',
    subcategory: 'cheekbones',
    prompt: 'Give the person softer less prominent cheekbones for a rounder face shape',
    icon: '⭕',
    intensity: 0.55,
  },

  // ============================================================
  // BODY
  // ============================================================
  {
    id: 'body-slimmer',
    name: 'Slimmer',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear slimmer and more toned',
    icon: '🧘',
    intensity: 0.70,
  },
  {
    id: 'body-athletic',
    name: 'Athletic',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear more muscular and athletic',
    icon: '🏃',
    intensity: 0.70,
  },
  {
    id: 'body-taller',
    name: 'Taller',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear taller with longer proportions',
    icon: '⬆️',
    intensity: 0.70,
  },
  {
    id: 'body-bodybuilder',
    name: 'Body Builder',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear as a muscular bodybuilder',
    icon: '💪',
    intensity: 0.70,
  },
  {
    id: 'body-curvier',
    name: 'Curvier',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear curvier with more defined curves',
    icon: '➰',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'body-hourglass',
    name: 'Hourglass',
    category: 'body',
    subcategory: 'body',
    prompt: 'Give the person an hourglass figure with defined waist',
    icon: '⏳',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'body-petite',
    name: 'Petite',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear petite with a smaller more delicate frame',
    icon: '🌷',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'body-broad-shoulders',
    name: 'Broad Shoulders',
    category: 'body',
    subcategory: 'body',
    prompt: 'Give the person broader more muscular shoulders',
    icon: '🔱',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'body-lean-ripped',
    name: 'Lean & Ripped',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear lean and ripped with visible muscle definition',
    icon: '🏋️',
    intensity: 0.70,
    gender: 'male',
  },

  // ============================================================
  // AGE-FANTASY - Age (6 items) — all neutral
  // ============================================================
  {
    id: 'age-10-younger',
    name: '10 Years Younger',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 10 years younger while preserving their identity',
    icon: '⏪',
    intensity: 0.70,
  },
  {
    id: 'age-20-younger',
    name: '20 Years Younger',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 20 years younger while preserving their identity',
    icon: '⏪',
    intensity: 0.70,
  },
  {
    id: 'age-teenage',
    name: 'Teenage',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look like a teenager while preserving their identity',
    icon: '🧒',
    intensity: 0.70,
  },
  {
    id: 'age-10-older',
    name: '10 Years Older',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 10 years older while preserving their identity',
    icon: '⏩',
    intensity: 0.70,
  },
  {
    id: 'age-20-older',
    name: '20 Years Older',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 20 years older while preserving their identity',
    icon: '⏩',
    intensity: 0.70,
  },
  {
    id: 'age-elderly',
    name: 'Elderly',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look elderly with wrinkles and gray hair while preserving their identity',
    icon: '🧓',
    intensity: 0.70,
  },

  // ============================================================
  // AGE-FANTASY - Fantasy (12 items) — all neutral
  // ============================================================
  {
    id: 'fantasy-elf',
    name: 'Elf',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a fantasy elf with pointed ears and ethereal features',
    icon: '🧝',
    intensity: 0.85,
  },
  {
    id: 'fantasy-vampire',
    name: 'Vampire',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a vampire with pale skin, fangs, and red eyes',
    icon: '🧛',
    intensity: 0.85,
  },
  {
    id: 'fantasy-zombie',
    name: 'Zombie',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a zombie with decaying skin and hollow eyes',
    icon: '🧟',
    intensity: 0.85,
  },
  {
    id: 'fantasy-alien',
    name: 'Alien',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into an alien with otherworldly features',
    icon: '👽',
    intensity: 0.85,
  },
  {
    id: 'fantasy-cyborg',
    name: 'Cyborg',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a cyborg with robotic mechanical parts on their face',
    icon: '🤖',
    intensity: 0.85,
  },
  {
    id: 'fantasy-fairy',
    name: 'Fairy',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a fairy with glowing skin and sparkly wings',
    icon: '🧚',
    intensity: 0.85,
  },
  {
    id: 'fantasy-mermaid',
    name: 'Mermaid',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a mermaid with iridescent scales and ocean-themed look',
    icon: '🧜',
    intensity: 0.85,
  },
  {
    id: 'fantasy-superhero',
    name: 'Superhero',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a superhero with a mask and cape',
    icon: '🦸',
    intensity: 0.85,
  },
  {
    id: 'fantasy-anime',
    name: 'Anime',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into an anime character with large eyes and stylized features',
    icon: '🎭',
    intensity: 0.85,
  },
  {
    id: 'fantasy-pixar',
    name: 'Pixar Character',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a Pixar 3D animated character',
    icon: '🎬',
    intensity: 0.85,
  },
  {
    id: 'fantasy-werewolf',
    name: 'Werewolf',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a werewolf with fur and sharp features',
    icon: '🐺',
    intensity: 0.85,
  },
  {
    id: 'fantasy-dragon-person',
    name: 'Dragon Person',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a dragon-human hybrid with scales and horns',
    icon: '🐉',
    intensity: 0.85,
  },
];

// ============================================================
// Helper Functions
// ============================================================

/**
 * Get subcategories filtered by gender.
 */
export function getSubcategoriesForGender(
  category: TransformationCategory,
  gender?: Gender | null,
): TransformationSubcategory[] {
  const subs = SUBCATEGORIES[category] ?? [];
  if (!gender) return subs.filter((s) => !s.gender);
  return subs.filter((s) => !s.gender || s.gender === gender);
}

/**
 * Get all transformations for a given category, optionally filtered by gender.
 */
export function getTransformationsByCategory(
  category: TransformationCategory,
  gender?: Gender | null,
): Transformation[] {
  return TRANSFORMATIONS.filter(
    (t) => t.category === category && (!t.gender || t.gender === gender),
  );
}

/**
 * Get all transformations for a given category and subcategory, optionally filtered by gender.
 */
export function getTransformationsBySubcategory(
  category: TransformationCategory,
  subcategory: string,
  gender?: Gender | null,
): Transformation[] {
  return TRANSFORMATIONS.filter(
    (t) =>
      t.category === category &&
      t.subcategory === subcategory &&
      (!t.gender || t.gender === gender),
  );
}

/**
 * Find a single transformation by its unique id.
 */
export function getTransformationById(id: string): Transformation | undefined {
  return TRANSFORMATIONS.find((t) => t.id === id);
}
