import type { Transformation, TransformationCategory, TransformationSubcategory } from '@/types';

export const CATEGORIES: Record<TransformationCategory, { name: string; icon: string; description: string }> = {
  hairstyles: {
    name: 'Hairstyles',
    icon: '\u2702\uFE0F',
    description: 'Change hair color, style, and length',
  },
  makeup: {
    name: 'Makeup',
    icon: '\uD83D\uDC84',
    description: 'Apply lipstick, eye makeup, and full looks',
  },
  clothing: {
    name: 'Clothing & Style',
    icon: '\uD83D\uDC54',
    description: 'Try on formal, casual, cultural, and decade-inspired outfits',
  },
  facial: {
    name: 'Facial Features',
    icon: '\u2728',
    description: 'Refine nose, jawline, eyes, lips, and cheekbones',
  },
  body: {
    name: 'Body & Shape',
    icon: '\uD83D\uDCAA',
    description: 'Transform body shape and proportions',
  },
  'age-fantasy': {
    name: 'Age & Fantasy',
    icon: '\uD83C\uDFAD',
    description: 'Age transformations and fantasy character styles',
  },
};

export const SUBCATEGORIES: Record<TransformationCategory, TransformationSubcategory[]> = {
  hairstyles: [
    { id: 'color', name: 'Color', icon: '\uD83C\uDFA8' },
    { id: 'style', name: 'Style', icon: '\uD83D\uDC87' },
    { id: 'length', name: 'Length', icon: '\uD83D\uDCCF' },
  ],
  makeup: [
    { id: 'lips', name: 'Lips', icon: '\uD83D\uDC8B' },
    { id: 'eyes', name: 'Eyes', icon: '\uD83D\uDC41\uFE0F' },
    { id: 'face', name: 'Face', icon: '\uD83E\uDDD6' },
    { id: 'full-looks', name: 'Full Looks', icon: '\uD83D\uDC83' },
  ],
  clothing: [
    { id: 'formal', name: 'Formal', icon: '\uD83E\uDD35' },
    { id: 'casual', name: 'Casual', icon: '\uD83D\uDC55' },
    { id: 'cultural', name: 'Cultural', icon: '\uD83C\uDF0D' },
    { id: 'decades', name: 'Decades', icon: '\u23F3' },
  ],
  facial: [
    { id: 'nose', name: 'Nose', icon: '\uD83D\uDC43' },
    { id: 'jawline', name: 'Jawline', icon: '\uD83D\uDDE3\uFE0F' },
    { id: 'eyes', name: 'Eyes', icon: '\uD83D\uDC40' },
    { id: 'lips', name: 'Lips', icon: '\uD83D\uDC44' },
    { id: 'cheekbones', name: 'Cheekbones', icon: '\uD83D\uDE18' },
  ],
  body: [
    { id: 'body', name: 'Body', icon: '\uD83E\uDDD1' },
  ],
  'age-fantasy': [
    { id: 'age', name: 'Age', icon: '\u231B' },
    { id: 'fantasy', name: 'Fantasy', icon: '\uD83E\uDDD9' },
  ],
};

export const TRANSFORMATIONS: Transformation[] = [
  // ============================================================
  // HAIRSTYLES - Color (14 items)
  // ============================================================
  {
    id: 'hair-color-blonde',
    name: 'Blonde',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to golden blonde while keeping everything else the same",
    icon: '\uD83D\uDC71',
    intensity: 0.65,
  },
  {
    id: 'hair-color-brunette',
    name: 'Brunette',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to rich brunette brown while keeping everything else the same",
    icon: '\uD83D\uDC69',
    intensity: 0.65,
  },
  {
    id: 'hair-color-red-auburn',
    name: 'Red/Auburn',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to red auburn while keeping everything else the same",
    icon: '\uD83E\uDDB0',
    intensity: 0.65,
  },
  {
    id: 'hair-color-black',
    name: 'Black',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to jet black while keeping everything else the same",
    icon: '\uD83D\uDDA4',
    intensity: 0.65,
  },
  {
    id: 'hair-color-platinum',
    name: 'Platinum',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to platinum white blonde while keeping everything else the same",
    icon: '\u2B50',
    intensity: 0.65,
  },
  {
    id: 'hair-color-silver-gray',
    name: 'Silver/Gray',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to silver gray while keeping everything else the same",
    icon: '\uD83E\uDD0D',
    intensity: 0.65,
  },
  {
    id: 'hair-color-pink',
    name: 'Pink',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to bright pink while keeping everything else the same",
    icon: '\uD83C\uDF38',
    intensity: 0.65,
  },
  {
    id: 'hair-color-blue',
    name: 'Blue',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to vibrant blue while keeping everything else the same",
    icon: '\uD83D\uDC99',
    intensity: 0.65,
  },
  {
    id: 'hair-color-purple',
    name: 'Purple',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to deep purple while keeping everything else the same",
    icon: '\uD83D\uDC9C',
    intensity: 0.65,
  },
  {
    id: 'hair-color-green',
    name: 'Green',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to emerald green while keeping everything else the same",
    icon: '\uD83D\uDC9A',
    intensity: 0.65,
  },
  {
    id: 'hair-color-ombre',
    name: 'Ombre',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair to an ombre style, dark roots transitioning to light blonde tips",
    icon: '\uD83C\uDF05',
    intensity: 0.65,
  },
  {
    id: 'hair-color-highlights',
    name: 'Highlights',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Add sun-kissed blonde highlights throughout the person's hair",
    icon: '\u2600\uFE0F',
    intensity: 0.65,
  },
  {
    id: 'hair-color-balayage',
    name: 'Balayage',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: 'Give the person a beautiful balayage hair coloring with natural-looking hand-painted highlights',
    icon: '\uD83C\uDF1F',
    intensity: 0.65,
  },
  {
    id: 'hair-color-rainbow',
    name: 'Rainbow',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair to rainbow colors with streaks of red, orange, yellow, green, blue, and purple",
    icon: '\uD83C\uDF08',
    intensity: 0.65,
  },

  // ============================================================
  // HAIRSTYLES - Style (18 items)
  // ============================================================
  {
    id: 'hair-style-bob',
    name: 'Bob',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a classic chin-length bob cut",
    icon: '\uD83D\uDC87',
    intensity: 0.70,
  },
  {
    id: 'hair-style-pixie',
    name: 'Pixie Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a short pixie cut",
    icon: '\uD83E\uDDD5',
    intensity: 0.70,
  },
  {
    id: 'hair-style-long-waves',
    name: 'Long Waves',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to long flowing wavy hair",
    icon: '\uD83C\uDF0A',
    intensity: 0.70,
  },
  {
    id: 'hair-style-curly',
    name: 'Curly',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to beautiful natural curly hair",
    icon: '\u27B0',
    intensity: 0.70,
  },
  {
    id: 'hair-style-straight',
    name: 'Straight',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to sleek straight hair",
    icon: '\u2712\uFE0F',
    intensity: 0.70,
  },
  {
    id: 'hair-style-braids',
    name: 'Braids',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to elegant braided hair",
    icon: '\uD83E\uDDF6',
    intensity: 0.70,
  },
  {
    id: 'hair-style-ponytail',
    name: 'Ponytail',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a high ponytail",
    icon: '\uD83C\uDF80',
    intensity: 0.70,
  },
  {
    id: 'hair-style-messy-bun',
    name: 'Messy Bun',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a casual messy bun",
    icon: '\uD83E\uDDF7',
    intensity: 0.70,
  },
  {
    id: 'hair-style-mohawk',
    name: 'Mohawk',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a bold mohawk",
    icon: '\uD83E\uDD18',
    intensity: 0.70,
  },
  {
    id: 'hair-style-buzz-cut',
    name: 'Buzz Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a very short buzz cut",
    icon: '\uD83D\uDC68\u200D\uD83E\uDDB2',
    intensity: 0.70,
  },
  {
    id: 'hair-style-undercut',
    name: 'Undercut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a trendy undercut with longer hair on top",
    icon: '\u2702\uFE0F',
    intensity: 0.70,
  },
  {
    id: 'hair-style-afro',
    name: 'Afro',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a full natural afro",
    icon: '\uD83E\uDDB1',
    intensity: 0.70,
  },
  {
    id: 'hair-style-locs',
    name: 'Locs',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to dreadlocks",
    icon: '\uD83E\uDDF5',
    intensity: 0.70,
  },
  {
    id: 'hair-style-box-braids',
    name: 'Box Braids',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to box braids",
    icon: '\uD83D\uDCAB',
    intensity: 0.70,
  },
  {
    id: 'hair-style-bangs',
    name: 'Bangs',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Add blunt bangs to the person's hairstyle while keeping the rest the same",
    icon: '\uD83D\uDE0E',
    intensity: 0.70,
  },
  {
    id: 'hair-style-mullet',
    name: 'Mullet',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a modern mullet",
    icon: '\uD83C\uDFB8',
    intensity: 0.70,
  },
  {
    id: 'hair-style-shag',
    name: 'Shag',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a layered shag cut",
    icon: '\uD83C\uDF3F',
    intensity: 0.70,
  },
  {
    id: 'hair-style-wolf-cut',
    name: 'Wolf Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a trendy wolf cut with choppy layers",
    icon: '\uD83D\uDC3A',
    intensity: 0.70,
  },

  // ============================================================
  // HAIRSTYLES - Length (5 items)
  // ============================================================
  {
    id: 'hair-length-very-short',
    name: 'Very Short/Crop',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to a very short cropped style",
    icon: '\u2702\uFE0F',
    intensity: 0.70,
  },
  {
    id: 'hair-length-short',
    name: 'Short',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to a short above-the-ears length",
    icon: '\uD83D\uDC48',
    intensity: 0.70,
  },
  {
    id: 'hair-length-medium',
    name: 'Medium',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to a medium shoulder-length",
    icon: '\u2194\uFE0F',
    intensity: 0.70,
  },
  {
    id: 'hair-length-long',
    name: 'Long',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to long hair reaching the middle of the back",
    icon: '\u2B07\uFE0F',
    intensity: 0.70,
  },
  {
    id: 'hair-length-very-long',
    name: 'Very Long',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to very long flowing hair reaching the waist",
    icon: '\uD83E\uDDDC',
    intensity: 0.70,
  },

  // ============================================================
  // MAKEUP - Lips (7 items)
  // ============================================================
  {
    id: 'makeup-lips-red',
    name: 'Red Lipstick',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply classic red lipstick to the person',
    icon: '\uD83D\uDC84',
    intensity: 0.60,
  },
  {
    id: 'makeup-lips-nude',
    name: 'Nude Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply natural nude lipstick to the person',
    icon: '\uD83E\uDD0E',
    intensity: 0.60,
  },
  {
    id: 'makeup-lips-pink',
    name: 'Pink Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply soft pink lipstick to the person',
    icon: '\uD83C\uDF38',
    intensity: 0.60,
  },
  {
    id: 'makeup-lips-bold-berry',
    name: 'Bold Berry',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply bold berry-colored lipstick to the person',
    icon: '\uD83C\uDF47',
    intensity: 0.60,
  },
  {
    id: 'makeup-lips-glossy',
    name: 'Glossy Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: "Apply shiny glossy lip gloss to the person's lips",
    icon: '\u2728',
    intensity: 0.60,
  },
  {
    id: 'makeup-lips-matte-dark',
    name: 'Matte Dark',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply dark matte burgundy lipstick to the person',
    icon: '\uD83D\uDDA4',
    intensity: 0.60,
  },
  {
    id: 'makeup-lips-ombre',
    name: 'Ombre Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply ombre lip color to the person, darker on the outside fading to lighter in the center',
    icon: '\uD83C\uDF05',
    intensity: 0.60,
  },

  // ============================================================
  // MAKEUP - Eyes (6 items)
  // ============================================================
  {
    id: 'makeup-eyes-smokey',
    name: 'Smokey Eye',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply dramatic smokey eye makeup with dark eyeshadow and blended edges to the person',
    icon: '\uD83C\uDF2B\uFE0F',
    intensity: 0.60,
  },
  {
    id: 'makeup-eyes-cat-eye',
    name: 'Cat Eye',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply cat eye winged eyeliner makeup to the person',
    icon: '\uD83D\uDC31',
    intensity: 0.60,
  },
  {
    id: 'makeup-eyes-natural',
    name: 'Natural Eyes',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply subtle natural eye makeup with light eyeshadow and thin eyeliner to the person',
    icon: '\uD83C\uDF3F',
    intensity: 0.60,
  },
  {
    id: 'makeup-eyes-glitter',
    name: 'Glitter Eyes',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply sparkly glitter eyeshadow makeup to the person',
    icon: '\uD83C\uDF1F',
    intensity: 0.60,
  },
  {
    id: 'makeup-eyes-dramatic-lashes',
    name: 'Dramatic Lashes',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply dramatic long false eyelashes to the person',
    icon: '\uD83E\uDEF6',
    intensity: 0.60,
  },
  {
    id: 'makeup-eyes-colored-contacts',
    name: 'Colored Contacts',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to bright blue",
    icon: '\uD83D\uDD35',
    intensity: 0.60,
  },

  // ============================================================
  // MAKEUP - Face (5 items)
  // ============================================================
  {
    id: 'makeup-face-clear-skin',
    name: 'Clear Skin',
    category: 'makeup',
    subcategory: 'face',
    prompt: 'Remove all makeup and give the person clear, natural, glowing skin',
    icon: '\u2728',
    intensity: 0.60,
  },
  {
    id: 'makeup-face-contoured',
    name: 'Contoured',
    category: 'makeup',
    subcategory: 'face',
    prompt: "Apply professional contouring makeup to the person's face, defining cheekbones and jawline",
    icon: '\uD83D\uDC8E',
    intensity: 0.60,
  },
  {
    id: 'makeup-face-bronzed-glow',
    name: 'Bronzed Glow',
    category: 'makeup',
    subcategory: 'face',
    prompt: 'Apply bronzer and highlighter to give the person a sun-kissed golden glow',
    icon: '\u2600\uFE0F',
    intensity: 0.60,
  },
  {
    id: 'makeup-face-dewy-skin',
    name: 'Dewy Skin',
    category: 'makeup',
    subcategory: 'face',
    prompt: 'Give the person dewy, glass-like skin with a luminous healthy glow',
    icon: '\uD83D\uDCA7',
    intensity: 0.60,
  },
  {
    id: 'makeup-face-freckles',
    name: 'Freckles',
    category: 'makeup',
    subcategory: 'face',
    prompt: "Add cute natural-looking freckles across the person's nose and cheeks",
    icon: '\uD83E\uDD0E',
    intensity: 0.60,
  },

  // ============================================================
  // MAKEUP - Full Looks (8 items)
  // ============================================================
  {
    id: 'makeup-full-natural-glam',
    name: 'Natural Glam',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply natural glamour makeup with subtle eyeshadow, mascara, light blush, and nude lip',
    icon: '\uD83C\uDF1F',
    intensity: 0.60,
  },
  {
    id: 'makeup-full-red-carpet',
    name: 'Red Carpet',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply full red carpet glamour makeup with smokey eyes, contoured face, and bold red lips',
    icon: '\uD83C\uDFC6',
    intensity: 0.60,
  },
  {
    id: 'makeup-full-gothic',
    name: 'Gothic',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply gothic dark makeup with black eyeshadow, dark lipstick, and pale foundation',
    icon: '\uD83E\uDDA7',
    intensity: 0.60,
  },
  {
    id: 'makeup-full-90s-supermodel',
    name: '90s Supermodel',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply 90s supermodel makeup with brown lip liner, matte lips, and defined brows',
    icon: '\uD83D\uDC60',
    intensity: 0.60,
  },
  {
    id: 'makeup-full-avant-garde',
    name: 'Avant-Garde',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply artistic avant-garde makeup with bold colors and creative designs',
    icon: '\uD83C\uDFA8',
    intensity: 0.60,
  },
  {
    id: 'makeup-full-k-beauty',
    name: 'K-Beauty',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply Korean beauty makeup style with gradient lips, subtle blush, and dewy skin',
    icon: '\uD83C\uDF38',
    intensity: 0.60,
  },
  {
    id: 'makeup-full-editorial',
    name: 'Editorial',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply high fashion editorial makeup with bold artistic elements',
    icon: '\uD83D\uDCF7',
    intensity: 0.60,
  },
  {
    id: 'makeup-full-bridal',
    name: 'Bridal',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply beautiful bridal wedding makeup with soft romantic tones and glowing skin',
    icon: '\uD83D\uDC70',
    intensity: 0.60,
  },

  // ============================================================
  // CLOTHING - Formal (4 items)
  // ============================================================
  {
    id: 'clothing-formal-business-suit',
    name: 'Business Suit',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a tailored professional business suit",
    icon: '\uD83D\uDCBC',
    intensity: 0.75,
  },
  {
    id: 'clothing-formal-tuxedo',
    name: 'Tuxedo',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with an elegant black tuxedo with bow tie",
    icon: '\uD83E\uDD35',
    intensity: 0.75,
  },
  {
    id: 'clothing-formal-evening-gown',
    name: 'Evening Gown',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a stunning floor-length evening gown",
    icon: '\uD83D\uDC57',
    intensity: 0.75,
  },
  {
    id: 'clothing-formal-cocktail-dress',
    name: 'Cocktail Dress',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a stylish cocktail dress",
    icon: '\uD83C\uDF78',
    intensity: 0.75,
  },

  // ============================================================
  // CLOTHING - Casual (5 items)
  // ============================================================
  {
    id: 'clothing-casual-streetwear',
    name: 'Streetwear',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with trendy urban streetwear",
    icon: '\uD83D\uDC5F',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-athleisure',
    name: 'Athleisure',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with stylish athletic athleisure wear",
    icon: '\uD83C\uDFC3',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-bohemian',
    name: 'Bohemian',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a bohemian flowing outfit with natural fabrics",
    icon: '\uD83C\uDF3B',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-preppy',
    name: 'Preppy',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a preppy outfit with polo shirt and clean lines",
    icon: '\uD83C\uDFCC\uFE0F',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-minimalist',
    name: 'Minimalist',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a minimalist modern outfit in neutral tones",
    icon: '\u25AB\uFE0F',
    intensity: 0.75,
  },

  // ============================================================
  // CLOTHING - Cultural (4 items)
  // ============================================================
  {
    id: 'clothing-cultural-kimono',
    name: 'Kimono',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with a beautiful traditional Japanese kimono",
    icon: '\uD83C\uDF8C',
    intensity: 0.75,
  },
  {
    id: 'clothing-cultural-sari',
    name: 'Sari',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with an elegant traditional Indian sari",
    icon: '\uD83E\uDD0E',
    intensity: 0.75,
  },
  {
    id: 'clothing-cultural-hanbok',
    name: 'Hanbok',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with a traditional Korean hanbok",
    icon: '\uD83C\uDDF0\uD83C\uDDF7',
    intensity: 0.75,
  },
  {
    id: 'clothing-cultural-scottish-highland',
    name: 'Scottish Highland',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with traditional Scottish highland dress with tartan kilt",
    icon: '\uD83C\uDFF4\uDB40\uDC67\uDB40\uDC62\uDB40\uDC73\uDB40\uDC63\uDB40\uDC74\uDB40\uDC7F',
    intensity: 0.75,
  },

  // ============================================================
  // CLOTHING - Decades (7 items)
  // ============================================================
  {
    id: 'clothing-decades-1950s',
    name: '1950s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1950s retro fashion",
    icon: '\uD83D\uDD7A',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1960s',
    name: '1960s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1960s mod fashion",
    icon: '\u262E\uFE0F',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1970s',
    name: '1970s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1970s disco fashion",
    icon: '\uD83D\uDD7A',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1980s',
    name: '1980s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1980s power fashion with bold colors and shoulder pads",
    icon: '\uD83C\uDF99\uFE0F',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1990s',
    name: '1990s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1990s grunge fashion",
    icon: '\uD83C\uDFB8',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-y2k',
    name: 'Y2K',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with Y2K fashion style",
    icon: '\uD83D\uDCBF',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-futuristic',
    name: 'Futuristic',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with futuristic sci-fi fashion",
    icon: '\uD83D\uDE80',
    intensity: 0.75,
  },

  // ============================================================
  // FACIAL - Nose (4 items)
  // ============================================================
  {
    id: 'facial-nose-smaller',
    name: 'Smaller',
    category: 'facial',
    subcategory: 'nose',
    prompt: "Make the person's nose slightly smaller and more refined while keeping their identity",
    icon: '\uD83D\uDC43',
    intensity: 0.55,
  },
  {
    id: 'facial-nose-button',
    name: 'Button Nose',
    category: 'facial',
    subcategory: 'nose',
    prompt: 'Give the person a cute button nose while keeping everything else the same',
    icon: '\uD83D\uDD18',
    intensity: 0.55,
  },
  {
    id: 'facial-nose-straight-bridge',
    name: 'Straight Bridge',
    category: 'facial',
    subcategory: 'nose',
    prompt: 'Give the person a straight nose bridge while keeping everything else the same',
    icon: '\u2796',
    intensity: 0.55,
  },
  {
    id: 'facial-nose-wider',
    name: 'Wider',
    category: 'facial',
    subcategory: 'nose',
    prompt: "Make the person's nose slightly wider while keeping everything else the same",
    icon: '\u2194\uFE0F',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Jawline (4 items)
  // ============================================================
  {
    id: 'facial-jawline-chiseled',
    name: 'Chiseled',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a sharper more chiseled jawline while keeping everything else the same',
    icon: '\uD83D\uDCA0',
    intensity: 0.55,
  },
  {
    id: 'facial-jawline-softer',
    name: 'Softer',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a softer more rounded jawline while keeping everything else the same',
    icon: '\u2B55',
    intensity: 0.55,
  },
  {
    id: 'facial-jawline-square',
    name: 'Square',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a strong square jawline while keeping everything else the same',
    icon: '\u25FE',
    intensity: 0.55,
  },
  {
    id: 'facial-jawline-v-shape',
    name: 'V-Shape',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a V-shaped jawline while keeping everything else the same',
    icon: '\u2714\uFE0F',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Eyes (4 items)
  // ============================================================
  {
    id: 'facial-eyes-larger',
    name: 'Larger Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Make the person's eyes slightly larger and more prominent",
    icon: '\uD83D\uDC40',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-almond',
    name: 'Almond Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: 'Give the person more almond-shaped eyes',
    icon: '\uD83C\uDF30',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-rounder',
    name: 'Rounder Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: 'Give the person rounder more open eyes',
    icon: '\u26AA',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-green',
    name: 'Green Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to vivid green",
    icon: '\uD83D\uDFE2',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Lips (4 items)
  // ============================================================
  {
    id: 'facial-lips-fuller',
    name: 'Fuller Lips',
    category: 'facial',
    subcategory: 'lips',
    prompt: 'Give the person fuller plumper lips while keeping everything else the same',
    icon: '\uD83D\uDC44',
    intensity: 0.55,
  },
  {
    id: 'facial-lips-thinner',
    name: 'Thinner Lips',
    category: 'facial',
    subcategory: 'lips',
    prompt: 'Give the person thinner more refined lips while keeping everything else the same',
    icon: '\u2796',
    intensity: 0.55,
  },
  {
    id: 'facial-lips-wider-smile',
    name: 'Wider Smile',
    category: 'facial',
    subcategory: 'lips',
    prompt: 'Give the person a wider more prominent smile',
    icon: '\uD83D\uDE01',
    intensity: 0.55,
  },
  {
    id: 'facial-lips-cupids-bow',
    name: "Cupid's Bow",
    category: 'facial',
    subcategory: 'lips',
    prompt: "Give the person more defined cupid's bow lips",
    icon: '\uD83C\uDFF9',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Cheekbones (3 items)
  // ============================================================
  {
    id: 'facial-cheekbones-higher',
    name: 'Higher',
    category: 'facial',
    subcategory: 'cheekbones',
    prompt: 'Give the person higher more prominent cheekbones',
    icon: '\u2B06\uFE0F',
    intensity: 0.55,
  },
  {
    id: 'facial-cheekbones-more-prominent',
    name: 'More Prominent',
    category: 'facial',
    subcategory: 'cheekbones',
    prompt: "Make the person's cheekbones more defined and sculpted",
    icon: '\uD83D\uDC8E',
    intensity: 0.55,
  },
  {
    id: 'facial-cheekbones-softer',
    name: 'Softer',
    category: 'facial',
    subcategory: 'cheekbones',
    prompt: 'Give the person softer less prominent cheekbones for a rounder face shape',
    icon: '\u2B55',
    intensity: 0.55,
  },

  // ============================================================
  // BODY - Body (5 items)
  // ============================================================
  {
    id: 'body-slimmer',
    name: 'Slimmer',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear slimmer and more toned',
    icon: '\uD83E\uDDD8',
    intensity: 0.70,
  },
  {
    id: 'body-athletic',
    name: 'Athletic',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear more muscular and athletic',
    icon: '\uD83C\uDFC3',
    intensity: 0.70,
  },
  {
    id: 'body-curvier',
    name: 'Curvier',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear curvier with more defined curves',
    icon: '\u27B0',
    intensity: 0.70,
  },
  {
    id: 'body-taller',
    name: 'Taller',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear taller with longer proportions',
    icon: '\u2B06\uFE0F',
    intensity: 0.70,
  },
  {
    id: 'body-bodybuilder',
    name: 'Body Builder',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear as a muscular bodybuilder',
    icon: '\uD83D\uDCAA',
    intensity: 0.70,
  },

  // ============================================================
  // AGE-FANTASY - Age (6 items)
  // ============================================================
  {
    id: 'age-10-younger',
    name: '10 Years Younger',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 10 years younger while preserving their identity',
    icon: '\u23EA',
    intensity: 0.70,
  },
  {
    id: 'age-20-younger',
    name: '20 Years Younger',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 20 years younger while preserving their identity',
    icon: '\u23EA',
    intensity: 0.70,
  },
  {
    id: 'age-teenage',
    name: 'Teenage',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look like a teenager while preserving their identity',
    icon: '\uD83E\uDDD2',
    intensity: 0.70,
  },
  {
    id: 'age-10-older',
    name: '10 Years Older',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 10 years older while preserving their identity',
    icon: '\u23E9',
    intensity: 0.70,
  },
  {
    id: 'age-20-older',
    name: '20 Years Older',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 20 years older while preserving their identity',
    icon: '\u23E9',
    intensity: 0.70,
  },
  {
    id: 'age-elderly',
    name: 'Elderly',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look elderly with wrinkles and gray hair while preserving their identity',
    icon: '\uD83E\uDDD3',
    intensity: 0.70,
  },

  // ============================================================
  // AGE-FANTASY - Fantasy (12 items)
  // ============================================================
  {
    id: 'fantasy-elf',
    name: 'Elf',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a fantasy elf with pointed ears and ethereal features',
    icon: '\uD83E\uDDDD',
    intensity: 0.85,
  },
  {
    id: 'fantasy-vampire',
    name: 'Vampire',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a vampire with pale skin, fangs, and red eyes',
    icon: '\uD83E\uDDDB',
    intensity: 0.85,
  },
  {
    id: 'fantasy-zombie',
    name: 'Zombie',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a zombie with decaying skin and hollow eyes',
    icon: '\uD83E\uDDDF',
    intensity: 0.85,
  },
  {
    id: 'fantasy-alien',
    name: 'Alien',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into an alien with otherworldly features',
    icon: '\uD83D\uDC7D',
    intensity: 0.85,
  },
  {
    id: 'fantasy-cyborg',
    name: 'Cyborg',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a cyborg with robotic mechanical parts on their face',
    icon: '\uD83E\uDD16',
    intensity: 0.85,
  },
  {
    id: 'fantasy-fairy',
    name: 'Fairy',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a fairy with glowing skin and sparkly wings',
    icon: '\uD83E\uDDDA',
    intensity: 0.85,
  },
  {
    id: 'fantasy-mermaid',
    name: 'Mermaid',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a mermaid with iridescent scales and ocean-themed look',
    icon: '\uD83E\uDDDC',
    intensity: 0.85,
  },
  {
    id: 'fantasy-superhero',
    name: 'Superhero',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a superhero with a mask and cape',
    icon: '\uD83E\uDDB8',
    intensity: 0.85,
  },
  {
    id: 'fantasy-anime',
    name: 'Anime',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into an anime character with large eyes and stylized features',
    icon: '\uD83C\uDFAD',
    intensity: 0.85,
  },
  {
    id: 'fantasy-pixar',
    name: 'Pixar Character',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a Pixar 3D animated character',
    icon: '\uD83C\uDFAC',
    intensity: 0.85,
  },
  {
    id: 'fantasy-werewolf',
    name: 'Werewolf',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a werewolf with fur and sharp features',
    icon: '\uD83D\uDC3A',
    intensity: 0.85,
  },
  {
    id: 'fantasy-dragon-person',
    name: 'Dragon Person',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a dragon-human hybrid with scales and horns',
    icon: '\uD83D\uDC09',
    intensity: 0.85,
  },
];

// ============================================================
// Helper Functions
// ============================================================

/**
 * Get all transformations for a given category.
 */
export function getTransformationsByCategory(category: TransformationCategory): Transformation[] {
  return TRANSFORMATIONS.filter((t) => t.category === category);
}

/**
 * Get all transformations for a given category and subcategory.
 */
export function getTransformationsBySubcategory(
  category: TransformationCategory,
  subcategory: string,
): Transformation[] {
  return TRANSFORMATIONS.filter((t) => t.category === category && t.subcategory === subcategory);
}

/**
 * Find a single transformation by its unique id.
 */
export function getTransformationById(id: string): Transformation | undefined {
  return TRANSFORMATIONS.find((t) => t.id === id);
}
