import type { Transformation, TransformationCategory, TransformationSubcategory, Gender } from '@/types';

export const CATEGORIES: Record<TransformationCategory, {
  name: string;
  maleName?: string;
  icon: string;
  maleIcon?: string;
  description: string;
}> = {
  hairstyles: {
    name: 'Hairstyles',
    icon: '✂️',
    description: 'Change hair color, style, and length',
  },
  makeup: {
    name: 'Makeup',
    maleName: 'Grooming',
    icon: '💄',
    maleIcon: '🪒',
    description: 'Apply lipstick, eye makeup, and full looks',
  },
  clothing: {
    name: 'Clothing & Style',
    icon: '👔',
    description: 'Try on formal, casual, cultural, and decade-inspired outfits',
  },
  accessories: {
    name: 'Accessories',
    icon: '💍',
    description: 'Add tattoos, piercings, jewelry, and headwear',
  },
  facial: {
    name: 'Facial Features',
    icon: '✨',
    description: 'Refine nose, jawline, eyes, lips, and cheekbones',
  },
  expression: {
    name: 'Expressions',
    icon: '😄',
    description: 'Change facial expressions and moods',
  },
  body: {
    name: 'Body & Shape',
    icon: '💪',
    description: 'Transform body shape and proportions',
  },
  'age-fantasy': {
    name: 'Age & Fantasy',
    icon: '🎭',
    description: 'Age transformations and fantasy character styles',
  },
  lighting: {
    name: 'Lighting',
    icon: '💡',
    description: 'Change lighting, mood, and atmosphere',
  },
};

export const SUBCATEGORIES: Record<TransformationCategory, TransformationSubcategory[]> = {
  hairstyles: [
    { id: 'color', name: 'Color', icon: '🎨' },
    { id: 'style', name: 'Style', icon: '💇' },
    { id: 'length', name: 'Length', icon: '📏' },
    { id: 'facial-hair', name: 'Facial Hair', icon: '🧔', gender: 'male' },
  ],
  makeup: [
    { id: 'lips', name: 'Lips', icon: '💋', gender: 'female' },
    { id: 'eyes', name: 'Eyes', icon: '👁️', gender: 'female' },
    { id: 'face', name: 'Face', icon: '🧖', gender: 'female' },
    { id: 'full-looks', name: 'Full Looks', icon: '🪄' },
    { id: 'skin', name: 'Skin', icon: '✨', gender: 'male' },
    { id: 'brows', name: 'Brows', icon: '🫤', gender: 'male' },
  ],
  clothing: [
    { id: 'formal', name: 'Formal', icon: '🤵' },
    { id: 'casual', name: 'Casual', icon: '👕' },
    { id: 'haute-couture', name: 'Haute Couture', icon: '👑' },
    { id: 'costumes', name: 'Costumes', icon: '🎃' },
    { id: 'cultural', name: 'Cultural', icon: '🌍' },
    { id: 'decades', name: 'Decades', icon: '⏳' },
  ],
  accessories: [
    { id: 'tattoos', name: 'Tattoos', icon: '🖋️' },
    { id: 'piercings', name: 'Piercings', icon: '📌' },
    { id: 'jewelry', name: 'Jewelry', icon: '💎' },
    { id: 'headwear', name: 'Headwear', icon: '🎩' },
    { id: 'eyewear', name: 'Eyewear', icon: '🕶️' },
  ],
  facial: [
    { id: 'nose', name: 'Nose', icon: '👃' },
    { id: 'jawline', name: 'Jawline', icon: '🗣️' },
    { id: 'eyes', name: 'Eyes', icon: '👀' },
    { id: 'lips', name: 'Lips', icon: '👄' },
    { id: 'cheekbones', name: 'Cheekbones', icon: '😘' },
  ],
  expression: [
    { id: 'mood', name: 'Mood', icon: '🎭' },
    { id: 'funny', name: 'Funny', icon: '🤪' },
  ],
  body: [
    { id: 'body', name: 'Body', icon: '🧑' },
  ],
  'age-fantasy': [
    { id: 'age', name: 'Age', icon: '⌛' },
    { id: 'fantasy', name: 'Fantasy', icon: '🧙' },
  ],
  lighting: [
    { id: 'lighting', name: 'Lighting', icon: '💡' },
  ],
};

export const TRANSFORMATIONS: Transformation[] = [
  // ============================================================
  // HAIRSTYLES - Color (14 items) — all neutral
  // ============================================================
  {
    id: 'hair-color-blonde',
    name: 'Blonde',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to golden blonde while keeping everything else the same",
    icon: '👱',
    intensity: 0.65,
  },
  {
    id: 'hair-color-brunette',
    name: 'Brunette',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to rich brunette brown while keeping everything else the same",
    icon: '👩',
    intensity: 0.65,
  },
  {
    id: 'hair-color-red-auburn',
    name: 'Red/Auburn',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to red auburn while keeping everything else the same",
    icon: '🦰',
    intensity: 0.65,
  },
  {
    id: 'hair-color-black',
    name: 'Black',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to jet black while keeping everything else the same",
    icon: '🖤',
    intensity: 0.65,
  },
  {
    id: 'hair-color-platinum',
    name: 'Platinum',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to platinum white blonde while keeping everything else the same",
    icon: '⭐',
    intensity: 0.65,
  },
  {
    id: 'hair-color-silver-gray',
    name: 'Silver/Gray',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to silver gray while keeping everything else the same",
    icon: '🤍',
    intensity: 0.65,
  },
  {
    id: 'hair-color-pink',
    name: 'Pink',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to bright pink while keeping everything else the same",
    icon: '🌸',
    intensity: 0.65,
  },
  {
    id: 'hair-color-blue',
    name: 'Blue',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to vibrant blue while keeping everything else the same",
    icon: '💙',
    intensity: 0.65,
  },
  {
    id: 'hair-color-purple',
    name: 'Purple',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to deep purple while keeping everything else the same",
    icon: '💜',
    intensity: 0.65,
  },
  {
    id: 'hair-color-green',
    name: 'Green',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair color to emerald green while keeping everything else the same",
    icon: '💚',
    intensity: 0.65,
  },
  {
    id: 'hair-color-ombre',
    name: 'Ombre',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair to an ombre style, dark roots transitioning to light blonde tips",
    icon: '🌅',
    intensity: 0.65,
  },
  {
    id: 'hair-color-highlights',
    name: 'Highlights',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Add sun-kissed blonde highlights throughout the person's hair",
    icon: '☀️',
    intensity: 0.65,
  },
  {
    id: 'hair-color-balayage',
    name: 'Balayage',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: 'Give the person a beautiful balayage hair coloring with natural-looking hand-painted highlights',
    icon: '🌟',
    intensity: 0.65,
  },
  {
    id: 'hair-color-rainbow',
    name: 'Rainbow',
    category: 'hairstyles',
    subcategory: 'color',
    prompt: "Change the person's hair to rainbow colors with streaks of red, orange, yellow, green, blue, and purple",
    icon: '🌈',
    intensity: 0.65,
  },

  // ============================================================
  // HAIRSTYLES - Style — neutral
  // ============================================================
  {
    id: 'hair-style-long-waves',
    name: 'Long Waves',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to long flowing wavy hair",
    icon: '🌊',
    intensity: 0.70,
  },
  {
    id: 'hair-style-curly',
    name: 'Curly',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to beautiful natural curly hair",
    icon: '➰',
    intensity: 0.70,
  },
  {
    id: 'hair-style-straight',
    name: 'Straight',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to sleek straight hair",
    icon: '✒️',
    intensity: 0.70,
  },
  {
    id: 'hair-style-braids',
    name: 'Braids',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to elegant braided hair",
    icon: '🧶',
    intensity: 0.70,
  },
  {
    id: 'hair-style-mohawk',
    name: 'Mohawk',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a bold mohawk",
    icon: '🤘',
    intensity: 0.70,
  },
  {
    id: 'hair-style-afro',
    name: 'Afro',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a full natural afro",
    icon: '🦱',
    intensity: 0.70,
  },
  {
    id: 'hair-style-locs',
    name: 'Locs',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to dreadlocks",
    icon: '🧵',
    intensity: 0.70,
  },
  {
    id: 'hair-style-box-braids',
    name: 'Box Braids',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to box braids",
    icon: '💫',
    intensity: 0.70,
  },
  {
    id: 'hair-style-mullet',
    name: 'Mullet',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a modern mullet",
    icon: '🎸',
    intensity: 0.70,
  },
  {
    id: 'hair-style-shag',
    name: 'Shag',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a layered shag cut",
    icon: '🌿',
    intensity: 0.70,
  },
  {
    id: 'hair-style-wolf-cut',
    name: 'Wolf Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a trendy wolf cut with choppy layers",
    icon: '🐺',
    intensity: 0.70,
  },
  {
    id: 'hair-style-bald',
    name: 'Bald',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Make the person completely bald with a clean shaved head, smooth scalp with no hair at all",
    icon: '🥚',
    intensity: 0.75,
  },
  {
    id: 'hair-style-bowl-cut',
    name: 'Bowl Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a classic bowl cut with straight bangs all around",
    icon: '🥣',
    intensity: 0.70,
  },
  {
    id: 'hair-style-liberty-spikes',
    name: 'Liberty Spikes',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to tall punk liberty spikes standing straight up",
    icon: '🦔',
    intensity: 0.75,
  },
  {
    id: 'hair-style-cornrows',
    name: 'Cornrows',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to neat tight cornrow braids close to the scalp",
    icon: '🌾',
    intensity: 0.70,
  },
  {
    id: 'hair-style-jheri-curl',
    name: 'Jheri Curl',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a glossy wet-look jheri curl",
    icon: '💦',
    intensity: 0.70,
  },
  {
    id: 'hair-style-rat-tail',
    name: 'Rat Tail',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a short cut with a long thin rat tail in the back",
    icon: '🐀',
    intensity: 0.70,
  },
  {
    id: 'hair-style-hi-top-fade',
    name: 'Hi-Top Fade',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a tall hi-top fade like Kid 'n Play",
    icon: '⬆️',
    intensity: 0.75,
  },
  {
    id: 'hair-style-devillock',
    name: 'Devillock',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a devillock with a long lock of hair hanging over the face",
    icon: '😈',
    intensity: 0.70,
  },

  // ============================================================
  // HAIRSTYLES - Style — female
  // ============================================================
  {
    id: 'hair-style-bob',
    name: 'Bob',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a classic chin-length bob cut",
    icon: '💇',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-pixie',
    name: 'Pixie Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a short pixie cut",
    icon: '🧕',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-ponytail',
    name: 'Ponytail',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a high ponytail",
    icon: '🎀',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-messy-bun',
    name: 'Messy Bun',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a casual messy bun",
    icon: '🧷',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-bangs',
    name: 'Bangs',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Add blunt bangs to the person's hairstyle while keeping the rest the same",
    icon: '😎',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-french-twist',
    name: 'French Twist',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to an elegant French twist updo",
    icon: '🌀',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-side-swept',
    name: 'Side Swept',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a glamorous side-swept style",
    icon: '💨',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-half-up',
    name: 'Half Up Half Down',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a half up half down style",
    icon: '⬆️',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-space-buns',
    name: 'Space Buns',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to playful space buns",
    icon: '🪐',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-curtain-bangs',
    name: 'Curtain Bangs',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Add curtain bangs to the person's hairstyle framing the face",
    icon: '🪟',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-layered',
    name: 'Layered',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a layered cut with face-framing layers",
    icon: '🍃',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-beehive',
    name: 'Beehive',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a tall retro beehive updo",
    icon: '🐝',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'hair-style-finger-waves',
    name: 'Finger Waves',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to elegant 1920s finger waves",
    icon: '👆',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-bald-female',
    name: 'Shaved Head',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Make the person completely bald with a clean shaved head, smooth scalp with no hair at all",
    icon: '✨',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'hair-style-double-buns',
    name: 'Double Buns',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to double buns on top of the head",
    icon: '🍡',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'hair-style-fishtail-braid',
    name: 'Fishtail Braid',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a long fishtail braid",
    icon: '🐟',
    intensity: 0.70,
    gender: 'female',
  },

  // ============================================================
  // HAIRSTYLES - Style — male
  // ============================================================
  {
    id: 'hair-style-buzz-cut',
    name: 'Buzz Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a very short buzz cut",
    icon: '👨‍🦲',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-undercut',
    name: 'Undercut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a trendy undercut with longer hair on top",
    icon: '✂️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-fade',
    name: 'Fade',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a clean fade haircut",
    icon: '💈',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-crew-cut',
    name: 'Crew Cut',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a classic crew cut",
    icon: '🪖',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-slick-back',
    name: 'Slick Back',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a slicked back style",
    icon: '🕴️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-man-bun',
    name: 'Man Bun',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a man bun",
    icon: '🔝',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-pompadour',
    name: 'Pompadour',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a classic pompadour",
    icon: '🎵',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-quiff',
    name: 'Quiff',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a modern quiff",
    icon: '🔼',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-comb-over',
    name: 'Comb Over',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a side-parted comb over",
    icon: '➡️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-flat-top',
    name: 'Flat Top',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a flat top",
    icon: '⬛',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-bald-beard',
    name: 'Bald + Beard',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Make the person completely bald with a clean shaved head and a thick full beard",
    icon: '🧔‍♂️',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'hair-style-skullet',
    name: 'Skullet',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a skullet - bald on top with long hair in the back",
    icon: '🤟',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'hair-style-high-and-tight',
    name: 'High & Tight',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to a military high and tight with very short sides",
    icon: '🎖️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-style-curtains-male',
    name: 'Curtains',
    category: 'hairstyles',
    subcategory: 'style',
    prompt: "Change the person's hairstyle to 90s curtains with a center part",
    icon: '🪟',
    intensity: 0.70,
    gender: 'male',
  },

  // ============================================================
  // HAIRSTYLES - Facial Hair (male only)
  // ============================================================
  {
    id: 'hair-facial-full-beard',
    name: 'Full Beard',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a full thick beard',
    icon: '🧔',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-stubble',
    name: 'Stubble',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person light stubble facial hair',
    icon: '🌫️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-goatee',
    name: 'Goatee',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a goatee beard on the chin',
    icon: '🎯',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-mustache',
    name: 'Mustache',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a classic mustache',
    icon: '🥸',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-handlebar',
    name: 'Handlebar Mustache',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a handlebar mustache with curled ends',
    icon: '〰️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-van-dyke',
    name: 'Van Dyke',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a Van Dyke beard with mustache and pointed chin beard',
    icon: '🎭',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-mutton-chops',
    name: 'Mutton Chops',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person mutton chop sideburns',
    icon: '🐑',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-soul-patch',
    name: 'Soul Patch',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a small soul patch below the lower lip',
    icon: '▪️',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-clean-shaven',
    name: 'Clean Shaven',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Make the person completely clean shaven with no facial hair',
    icon: '✨',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-five-oclock',
    name: "5 O'Clock Shadow",
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: "Give the person a 5 o'clock shadow with slight stubble",
    icon: '🕐',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-lumberjack',
    name: 'Lumberjack Beard',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a big rugged lumberjack beard',
    icon: '🪓',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'hair-facial-chinstrap',
    name: 'Chinstrap',
    category: 'hairstyles',
    subcategory: 'facial-hair',
    prompt: 'Give the person a thin chinstrap beard along the jawline',
    icon: '⛓️',
    intensity: 0.70,
    gender: 'male',
  },

  // ============================================================
  // HAIRSTYLES - Length (5 items) — all neutral
  // ============================================================
  {
    id: 'hair-length-very-short',
    name: 'Very Short/Crop',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to a very short cropped style",
    icon: '✂️',
    intensity: 0.70,
  },
  {
    id: 'hair-length-short',
    name: 'Short',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to a short above-the-ears length",
    icon: '👈',
    intensity: 0.70,
  },
  {
    id: 'hair-length-medium',
    name: 'Medium',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to a medium shoulder-length",
    icon: '↔️',
    intensity: 0.70,
  },
  {
    id: 'hair-length-long',
    name: 'Long',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to long hair reaching the middle of the back",
    icon: '⬇️',
    intensity: 0.70,
  },
  {
    id: 'hair-length-very-long',
    name: 'Very Long',
    category: 'hairstyles',
    subcategory: 'length',
    prompt: "Change the person's hair to very long flowing hair reaching the waist",
    icon: '🧜',
    intensity: 0.70,
  },

  // ============================================================
  // MAKEUP - Lips (7 items) — all female
  // ============================================================
  {
    id: 'makeup-lips-red',
    name: 'Red Lipstick',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply classic red lipstick to the person',
    icon: '💄',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-nude',
    name: 'Nude Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply natural nude lipstick to the person',
    icon: '🤎',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-pink',
    name: 'Pink Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply soft pink lipstick to the person',
    icon: '🌸',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-bold-berry',
    name: 'Bold Berry',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply bold berry-colored lipstick to the person',
    icon: '🍇',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-glossy',
    name: 'Glossy Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: "Apply shiny glossy lip gloss to the person's lips",
    icon: '✨',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-matte-dark',
    name: 'Matte Dark',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply dark matte burgundy lipstick to the person',
    icon: '🖤',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-lips-ombre',
    name: 'Ombre Lips',
    category: 'makeup',
    subcategory: 'lips',
    prompt: 'Apply ombre lip color to the person, darker on the outside fading to lighter in the center',
    icon: '🌅',
    intensity: 0.60,
    gender: 'female',
  },

  // ============================================================
  // MAKEUP - Eyes (6 items) — all female
  // ============================================================
  {
    id: 'makeup-eyes-smokey',
    name: 'Smokey Eye',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply dramatic smokey eye makeup with dark eyeshadow and blended edges to the person',
    icon: '🌫️',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-cat-eye',
    name: 'Cat Eye',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply cat eye winged eyeliner makeup to the person',
    icon: '🐱',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-natural',
    name: 'Natural Eyes',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply subtle natural eye makeup with light eyeshadow and thin eyeliner to the person',
    icon: '🌿',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-glitter',
    name: 'Glitter Eyes',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply sparkly glitter eyeshadow makeup to the person',
    icon: '🌟',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-dramatic-lashes',
    name: 'Dramatic Lashes',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: 'Apply dramatic long false eyelashes to the person',
    icon: '🫶',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-eyes-colored-contacts',
    name: 'Colored Contacts',
    category: 'makeup',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to bright blue",
    icon: '🔵',
    intensity: 0.60,
    gender: 'female',
  },

  // ============================================================
  // MAKEUP - Face (5 items) — all female
  // ============================================================
  {
    id: 'makeup-face-clear-skin',
    name: 'Clear Skin',
    category: 'makeup',
    subcategory: 'face',
    prompt: 'Remove all makeup and give the person clear, natural, glowing skin',
    icon: '✨',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-face-contoured',
    name: 'Contoured',
    category: 'makeup',
    subcategory: 'face',
    prompt: "Apply professional contouring makeup to the person's face, defining cheekbones and jawline",
    icon: '💎',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-face-bronzed-glow',
    name: 'Bronzed Glow',
    category: 'makeup',
    subcategory: 'face',
    prompt: 'Apply bronzer and highlighter to give the person a sun-kissed golden glow',
    icon: '☀️',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-face-dewy-skin',
    name: 'Dewy Skin',
    category: 'makeup',
    subcategory: 'face',
    prompt: 'Give the person dewy, glass-like skin with a luminous healthy glow',
    icon: '💧',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-face-freckles',
    name: 'Freckles',
    category: 'makeup',
    subcategory: 'face',
    prompt: "Add cute natural-looking freckles across the person's nose and cheeks",
    icon: '🤎',
    intensity: 0.60,
    gender: 'female',
  },

  // ============================================================
  // MAKEUP - Full Looks (8 items) — female
  // ============================================================
  {
    id: 'makeup-full-natural-glam',
    name: 'Natural Glam',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply natural glamour makeup with subtle eyeshadow, mascara, light blush, and nude lip',
    icon: '🌟',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-red-carpet',
    name: 'Red Carpet',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply full red carpet glamour makeup with smokey eyes, contoured face, and bold red lips',
    icon: '🏆',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-gothic',
    name: 'Gothic',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply gothic dark makeup with black eyeshadow, dark lipstick, and pale foundation',
    icon: '🦇',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-90s-supermodel',
    name: '90s Supermodel',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply 90s supermodel makeup with brown lip liner, matte lips, and defined brows',
    icon: '👠',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-avant-garde',
    name: 'Avant-Garde',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply artistic avant-garde makeup with bold colors and creative designs',
    icon: '🎨',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-k-beauty',
    name: 'K-Beauty',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply Korean beauty makeup style with gradient lips, subtle blush, and dewy skin',
    icon: '🌸',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-editorial',
    name: 'Editorial',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply high fashion editorial makeup with bold artistic elements',
    icon: '📷',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'makeup-full-bridal',
    name: 'Bridal',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Apply beautiful bridal wedding makeup with soft romantic tones and glowing skin',
    icon: '👰',
    intensity: 0.60,
    gender: 'female',
  },

  // ============================================================
  // GROOMING - Skin (male)
  // ============================================================
  {
    id: 'grooming-skin-clear',
    name: 'Clear Skin',
    category: 'makeup',
    subcategory: 'skin',
    prompt: 'Give the person clear blemish-free skin with a natural healthy look',
    icon: '✨',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-skin-bronzed',
    name: 'Bronzed',
    category: 'makeup',
    subcategory: 'skin',
    prompt: 'Give the person a sun-kissed bronzed skin tone',
    icon: '☀️',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-skin-matte',
    name: 'Matte Skin',
    category: 'makeup',
    subcategory: 'skin',
    prompt: 'Give the person smooth matte skin with no shine',
    icon: '🪨',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-skin-healthy-glow',
    name: 'Healthy Glow',
    category: 'makeup',
    subcategory: 'skin',
    prompt: 'Give the person healthy glowing skin with a natural radiance',
    icon: '💡',
    intensity: 0.60,
    gender: 'male',
  },

  // ============================================================
  // GROOMING - Brows (male)
  // ============================================================
  {
    id: 'grooming-brows-thick',
    name: 'Thick Brows',
    category: 'makeup',
    subcategory: 'brows',
    prompt: 'Give the person thick bold eyebrows',
    icon: '🟫',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-brows-groomed',
    name: 'Groomed Brows',
    category: 'makeup',
    subcategory: 'brows',
    prompt: 'Give the person neatly groomed and shaped eyebrows',
    icon: '✂️',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-brows-bushy',
    name: 'Bushy Brows',
    category: 'makeup',
    subcategory: 'brows',
    prompt: 'Give the person natural bushy eyebrows',
    icon: '🌿',
    intensity: 0.60,
    gender: 'male',
  },

  // ============================================================
  // GROOMING - Full Looks (male)
  // ============================================================
  {
    id: 'grooming-full-well-groomed',
    name: 'Well-Groomed',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Give the person a polished well-groomed look with clean skin and neat facial hair',
    icon: '👔',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-full-rugged',
    name: 'Rugged',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Give the person a rugged masculine look with textured skin and slight stubble',
    icon: '🏔️',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-full-pretty-boy',
    name: 'Pretty Boy',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Give the person a refined pretty boy look with flawless skin and defined features',
    icon: '💎',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'grooming-full-distinguished',
    name: 'Distinguished',
    category: 'makeup',
    subcategory: 'full-looks',
    prompt: 'Give the person a distinguished mature look with subtle gray at the temples and refined features',
    icon: '🎩',
    intensity: 0.60,
    gender: 'male',
  },

  // ============================================================
  // CLOTHING - Formal
  // ============================================================
  {
    id: 'clothing-formal-business-suit',
    name: 'Business Suit',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a tailored professional business suit",
    icon: '💼',
    intensity: 0.75,
  },
  {
    id: 'clothing-formal-tuxedo',
    name: 'Tuxedo',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with an elegant black tuxedo with bow tie",
    icon: '🤵',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-formal-three-piece',
    name: 'Three-Piece Suit',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a classic three-piece suit with vest",
    icon: '🤵',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-formal-military',
    name: 'Military Dress',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a formal military dress uniform",
    icon: '🎖️',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-formal-evening-gown',
    name: 'Evening Gown',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a stunning floor-length evening gown",
    icon: '👗',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-formal-cocktail-dress',
    name: 'Cocktail Dress',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a stylish cocktail dress",
    icon: '🍸',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-formal-ball-gown',
    name: 'Ball Gown',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a grand ball gown with flowing skirt",
    icon: '👸',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-formal-jumpsuit',
    name: 'Jumpsuit',
    category: 'clothing',
    subcategory: 'formal',
    prompt: "Replace the person's outfit with a sleek tailored jumpsuit",
    icon: '🦸‍♀️',
    intensity: 0.75,
    gender: 'female',
  },

  // ============================================================
  // CLOTHING - Casual
  // ============================================================
  {
    id: 'clothing-casual-streetwear',
    name: 'Streetwear',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with trendy urban streetwear",
    icon: '👟',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-athleisure',
    name: 'Athleisure',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with stylish athletic athleisure wear",
    icon: '🏃',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-bohemian',
    name: 'Bohemian',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a bohemian flowing outfit with natural fabrics",
    icon: '🌻',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-preppy',
    name: 'Preppy',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a preppy outfit with polo shirt and clean lines",
    icon: '🏌️',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-minimalist',
    name: 'Minimalist',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a minimalist modern outfit in neutral tones",
    icon: '▫️',
    intensity: 0.75,
  },
  {
    id: 'clothing-casual-workwear',
    name: 'Workwear',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with rugged workwear with boots and denim",
    icon: '🔧',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-casual-biker',
    name: 'Biker',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a leather biker jacket and boots",
    icon: '🏍️',
    intensity: 0.75,
    gender: 'male',
  },
  {
    id: 'clothing-casual-cottagecore',
    name: 'Cottagecore',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with a cottagecore outfit with floral dress and natural fabrics",
    icon: '🌸',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-casual-y2k-girly',
    name: 'Y2K Girly',
    category: 'clothing',
    subcategory: 'casual',
    prompt: "Replace the person's outfit with Y2K girly fashion with low-rise and baby tees",
    icon: '💖',
    intensity: 0.75,
    gender: 'female',
  },

  // ============================================================
  // CLOTHING - Cultural (4 items) — all neutral
  // ============================================================
  {
    id: 'clothing-cultural-kimono',
    name: 'Kimono',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with a beautiful traditional Japanese kimono",
    icon: '🎌',
    intensity: 0.75,
  },
  {
    id: 'clothing-cultural-sari',
    name: 'Sari',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with an elegant traditional Indian sari",
    icon: '🤎',
    intensity: 0.75,
    gender: 'female',
  },
  {
    id: 'clothing-cultural-hanbok',
    name: 'Hanbok',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with a traditional Korean hanbok",
    icon: '🇰🇷',
    intensity: 0.75,
  },
  {
    id: 'clothing-cultural-scottish-highland',
    name: 'Scottish Highland',
    category: 'clothing',
    subcategory: 'cultural',
    prompt: "Replace the person's outfit with traditional Scottish highland dress with tartan kilt",
    icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    intensity: 0.75,
  },

  // ============================================================
  // CLOTHING - Decades (7 items) — all neutral
  // ============================================================
  {
    id: 'clothing-decades-1950s',
    name: '1950s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1950s retro fashion",
    icon: '🕺',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1960s',
    name: '1960s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1960s mod fashion",
    icon: '☮️',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1970s',
    name: '1970s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1970s disco fashion",
    icon: '🕺',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1980s',
    name: '1980s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1980s power fashion with bold colors and shoulder pads",
    icon: '🎙️',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1990s',
    name: '1990s',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1990s grunge fashion",
    icon: '🎸',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-y2k',
    name: 'Y2K',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with Y2K fashion style",
    icon: '💿',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-futuristic',
    name: 'Futuristic',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with futuristic sci-fi fashion",
    icon: '🚀',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1920s',
    name: '1920s Gatsby',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1920s Great Gatsby era fashion with Art Deco glamour",
    icon: '🥂',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1930s',
    name: '1930s Hollywood',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1930s Old Hollywood glamour fashion",
    icon: '🎬',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-1940s',
    name: '1940s Wartime',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with 1940s wartime era fashion with military-inspired tailoring",
    icon: '🪖',
    intensity: 0.75,
  },
  {
    id: 'clothing-decades-victorian',
    name: 'Victorian',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with Victorian era clothing with high collars and ornate details",
    icon: '🏰',
    intensity: 0.80,
  },
  {
    id: 'clothing-decades-renaissance',
    name: 'Renaissance',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with Renaissance era clothing with rich fabrics and elaborate details",
    icon: '🎨',
    intensity: 0.80,
  },
  {
    id: 'clothing-decades-medieval',
    name: 'Medieval',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with medieval clothing like a tunic, chainmail, or royal robes",
    icon: '⚔️',
    intensity: 0.80,
  },
  {
    id: 'clothing-decades-ancient-roman',
    name: 'Ancient Roman',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with ancient Roman toga and laurel wreath",
    icon: '🏛️',
    intensity: 0.80,
  },
  {
    id: 'clothing-decades-regency',
    name: 'Regency Era',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with Regency era Bridgerton-style clothing with empire waists and elegant tailoring",
    icon: '🫖',
    intensity: 0.80,
  },
  {
    id: 'clothing-decades-ancient-egyptian',
    name: 'Ancient Egyptian',
    category: 'clothing',
    subcategory: 'decades',
    prompt: "Replace the person's outfit with ancient Egyptian royal clothing with gold jewelry and headdress",
    icon: '🏺',
    intensity: 0.80,
  },

  // ============================================================
  // CLOTHING - Haute Couture
  // ============================================================
  {
    id: 'clothing-couture-met-gala',
    name: 'Met Gala',
    category: 'clothing',
    subcategory: 'haute-couture',
    prompt: "Replace the person's outfit with an extravagant Met Gala red carpet look with dramatic avant-garde fashion",
    icon: '🌟',
    intensity: 0.80,
  },
  {
    id: 'clothing-couture-runway',
    name: 'Runway Model',
    category: 'clothing',
    subcategory: 'haute-couture',
    prompt: "Replace the person's outfit with high fashion runway model clothing from a Paris fashion week show",
    icon: '👠',
    intensity: 0.80,
  },
  {
    id: 'clothing-couture-avantgarde',
    name: 'Avant-Garde',
    category: 'clothing',
    subcategory: 'haute-couture',
    prompt: "Replace the person's outfit with dramatic avant-garde fashion with sculptural shapes and unconventional materials",
    icon: '🎭',
    intensity: 0.80,
  },
  {
    id: 'clothing-couture-ballroom',
    name: 'Ballroom Gala',
    category: 'clothing',
    subcategory: 'haute-couture',
    prompt: "Replace the person's outfit with an opulent ballroom gala ensemble with luxurious fabrics and intricate beading",
    icon: '💃',
    intensity: 0.80,
  },
  {
    id: 'clothing-couture-editorial',
    name: 'Editorial',
    category: 'clothing',
    subcategory: 'haute-couture',
    prompt: "Replace the person's outfit with high fashion editorial magazine cover clothing, bold and artistic",
    icon: '📸',
    intensity: 0.80,
  },
  {
    id: 'clothing-couture-monochrome',
    name: 'All White',
    category: 'clothing',
    subcategory: 'haute-couture',
    prompt: "Replace the person's outfit with an all-white haute couture ensemble, luxurious and elegant",
    icon: '🤍',
    intensity: 0.80,
  },
  {
    id: 'clothing-couture-all-black',
    name: 'All Black',
    category: 'clothing',
    subcategory: 'haute-couture',
    prompt: "Replace the person's outfit with an all-black high fashion ensemble, sleek and sophisticated",
    icon: '🖤',
    intensity: 0.80,
  },
  {
    id: 'clothing-couture-feathers',
    name: 'Feathered Look',
    category: 'clothing',
    subcategory: 'haute-couture',
    prompt: "Replace the person's outfit with a dramatic feathered haute couture outfit covered in luxurious feathers",
    icon: '🪶',
    intensity: 0.80,
  },

  // ============================================================
  // CLOTHING - Costumes & Fun Dress Up
  // ============================================================
  {
    id: 'clothing-costume-cowboy',
    name: 'Cowboy',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a Western cowboy outfit with hat, boots, and denim",
    icon: '🤠',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-astronaut',
    name: 'Astronaut',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a NASA astronaut spacesuit",
    icon: '🧑‍🚀',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-rockstar',
    name: 'Rock Star',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a rock star outfit with leather, studs, and chains",
    icon: '🎸',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-disco',
    name: 'Disco',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a full 70s disco outfit with sequins and bell-bottoms",
    icon: '🪩',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-hawaiian',
    name: 'Hawaiian Tourist',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a loud Hawaiian tourist shirt and lei flower necklace",
    icon: '🌺',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-chef',
    name: 'Chef',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a professional chef uniform with white coat and tall chef hat",
    icon: '👨‍🍳',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-pirate',
    name: 'Pirate',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a pirate costume with tricorn hat, eyepatch, and ruffled shirt",
    icon: '🏴‍☠️',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-ninja',
    name: 'Ninja',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a black ninja outfit with mask and hood",
    icon: '🥷',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-wizard',
    name: 'Wizard',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a wizard robe and pointed hat with stars and moons",
    icon: '🧙',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-knight',
    name: 'Knight',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a medieval knight's shining armor with helmet",
    icon: '🛡️',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-safari',
    name: 'Safari',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a safari explorer outfit with khaki vest and pith helmet",
    icon: '🦁',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-lumberjack',
    name: 'Lumberjack',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a lumberjack outfit with plaid flannel shirt and suspenders",
    icon: '🪓',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-punk',
    name: 'Punk',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a punk outfit with spiked leather jacket, safety pins, and patches",
    icon: '🤘',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-rapper',
    name: 'Rapper',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a hip-hop rapper outfit with oversized chains, cap, and designer clothing",
    icon: '🎤',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-royal',
    name: 'Royalty',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with royal king or queen robes with a crown and ermine cape",
    icon: '👑',
    intensity: 0.80,
  },
  {
    id: 'clothing-costume-athlete',
    name: 'Pro Athlete',
    category: 'clothing',
    subcategory: 'costumes',
    prompt: "Replace the person's outfit with a professional athlete's jersey and gear",
    icon: '🏆',
    intensity: 0.80,
  },

  // ============================================================
  // ACCESSORIES - Tattoos
  // ============================================================
  {
    id: 'acc-tattoo-sleeve',
    name: 'Full Sleeve',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add a full sleeve tattoo covering the person's entire arm with intricate detailed designs",
    icon: '💪',
    intensity: 0.65,
  },
  {
    id: 'acc-tattoo-face',
    name: 'Face Tattoo',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add small face tattoos on the person's face, like a tear drop and small symbols near the temples",
    icon: '💧',
    intensity: 0.60,
  },
  {
    id: 'acc-tattoo-neck',
    name: 'Neck Tattoo',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add a bold neck tattoo on the person with detailed designs covering the neck and throat",
    icon: '🖋️',
    intensity: 0.65,
  },
  {
    id: 'acc-tattoo-hand',
    name: 'Hand Tattoos',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add tattoos on the person's hands and fingers with intricate designs and lettering on the knuckles",
    icon: '🤚',
    intensity: 0.65,
  },
  {
    id: 'acc-tattoo-chest',
    name: 'Chest Piece',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add a large chest tattoo visible at the neckline with an ornate design",
    icon: '🦅',
    intensity: 0.65,
  },
  {
    id: 'acc-tattoo-tribal',
    name: 'Tribal',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add bold black tribal tattoos on the person's arms and shoulders with flowing geometric patterns",
    icon: '🔱',
    intensity: 0.65,
  },
  {
    id: 'acc-tattoo-japanese',
    name: 'Japanese Style',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add Japanese style tattoos with koi fish, waves, and cherry blossoms on the person's arms",
    icon: '🎏',
    intensity: 0.65,
  },
  {
    id: 'acc-tattoo-minimalist',
    name: 'Minimalist',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add small minimalist fine-line tattoos on the person's arms and collarbone area",
    icon: '✨',
    intensity: 0.60,
  },
  {
    id: 'acc-tattoo-old-school',
    name: 'Old School',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add old school traditional American style tattoos with bold lines, roses, anchors, and eagles on the person's arms",
    icon: '⚓',
    intensity: 0.65,
  },
  {
    id: 'acc-tattoo-blackwork',
    name: 'Blackwork',
    category: 'accessories',
    subcategory: 'tattoos',
    prompt: "Add heavy blackwork tattoos with solid black geometric shapes and patterns covering the person's arms",
    icon: '⬛',
    intensity: 0.65,
  },

  // ============================================================
  // ACCESSORIES - Piercings
  // ============================================================
  {
    id: 'acc-piercing-nose-ring',
    name: 'Nose Ring',
    category: 'accessories',
    subcategory: 'piercings',
    prompt: 'Add a small gold nose ring piercing on the side of the nostril',
    icon: '👃',
    intensity: 0.55,
  },
  {
    id: 'acc-piercing-septum',
    name: 'Septum',
    category: 'accessories',
    subcategory: 'piercings',
    prompt: 'Add a septum ring piercing hanging from the center of the nose',
    icon: '🐂',
    intensity: 0.55,
  },
  {
    id: 'acc-piercing-lip-ring',
    name: 'Lip Ring',
    category: 'accessories',
    subcategory: 'piercings',
    prompt: 'Add a small silver lip ring piercing on the lower lip',
    icon: '💋',
    intensity: 0.55,
  },
  {
    id: 'acc-piercing-eyebrow',
    name: 'Eyebrow',
    category: 'accessories',
    subcategory: 'piercings',
    prompt: 'Add a small barbell eyebrow piercing above one eye',
    icon: '📎',
    intensity: 0.55,
  },
  {
    id: 'acc-piercing-multiple-ear',
    name: 'Multiple Ear',
    category: 'accessories',
    subcategory: 'piercings',
    prompt: "Add multiple ear piercings with several small hoops and studs running up the person's ears",
    icon: '👂',
    intensity: 0.55,
  },
  {
    id: 'acc-piercing-industrial',
    name: 'Industrial',
    category: 'accessories',
    subcategory: 'piercings',
    prompt: 'Add an industrial barbell piercing through the upper ear cartilage',
    icon: '🔩',
    intensity: 0.55,
  },
  {
    id: 'acc-piercing-medusa',
    name: 'Medusa',
    category: 'accessories',
    subcategory: 'piercings',
    prompt: 'Add a medusa piercing (philtrum) centered above the upper lip',
    icon: '✧',
    intensity: 0.55,
  },
  {
    id: 'acc-piercing-snakebites',
    name: 'Snake Bites',
    category: 'accessories',
    subcategory: 'piercings',
    prompt: 'Add snake bite piercings - two symmetrical piercings on either side of the lower lip',
    icon: '🐍',
    intensity: 0.55,
  },

  // ============================================================
  // ACCESSORIES - Jewelry
  // ============================================================
  {
    id: 'acc-jewelry-diamond-necklace',
    name: 'Diamond Necklace',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add a stunning diamond necklace around the neck, sparkling and luxurious',
    icon: '💎',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'acc-jewelry-pearl-necklace',
    name: 'Pearl Necklace',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add an elegant string of pearls necklace around the neck',
    icon: '🫧',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'acc-jewelry-statement-earrings',
    name: 'Statement Earrings',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add large glamorous statement chandelier earrings that catch the light',
    icon: '✨',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'acc-jewelry-tiara',
    name: 'Tiara',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add a sparkling crystal tiara crown on top of the head like a princess',
    icon: '👸',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'acc-jewelry-choker',
    name: 'Choker',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add a stylish velvet or diamond choker necklace tight around the neck',
    icon: '⭕',
    intensity: 0.60,
    gender: 'female',
  },
  {
    id: 'acc-jewelry-gold-chain',
    name: 'Gold Chain',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add a thick gold chain necklace around the neck',
    icon: '🔗',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'acc-jewelry-watch-rings',
    name: 'Watch & Rings',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add a luxury watch and gold rings on the fingers',
    icon: '⌚',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'acc-jewelry-cuban-link',
    name: 'Cuban Link',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add a heavy iced-out Cuban link chain necklace with diamonds',
    icon: '💰',
    intensity: 0.60,
    gender: 'male',
  },
  {
    id: 'acc-jewelry-diamond-studs',
    name: 'Diamond Studs',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add sparkling diamond stud earrings in both ears',
    icon: '💠',
    intensity: 0.55,
  },
  {
    id: 'acc-jewelry-hoop-earrings',
    name: 'Hoop Earrings',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add large gold hoop earrings',
    icon: '⭕',
    intensity: 0.55,
  },
  {
    id: 'acc-jewelry-pendant',
    name: 'Pendant',
    category: 'accessories',
    subcategory: 'jewelry',
    prompt: 'Add a beautiful pendant necklace on a delicate chain',
    icon: '🧿',
    intensity: 0.55,
  },

  // ============================================================
  // ACCESSORIES - Headwear
  // ============================================================
  {
    id: 'acc-headwear-cowboy-hat',
    name: 'Cowboy Hat',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a Western cowboy hat on the person',
    icon: '🤠',
    intensity: 0.65,
  },
  {
    id: 'acc-headwear-top-hat',
    name: 'Top Hat',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a classic black top hat on the person like a gentleman',
    icon: '🎩',
    intensity: 0.65,
  },
  {
    id: 'acc-headwear-flower-crown',
    name: 'Flower Crown',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a beautiful flower crown wreath on top of the head with colorful fresh flowers',
    icon: '🌸',
    intensity: 0.60,
  },
  {
    id: 'acc-headwear-beanie',
    name: 'Beanie',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a cozy knit beanie hat on the person',
    icon: '🧶',
    intensity: 0.65,
  },
  {
    id: 'acc-headwear-fedora',
    name: 'Fedora',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a stylish fedora hat on the person',
    icon: '🎩',
    intensity: 0.65,
  },
  {
    id: 'acc-headwear-crown',
    name: 'Royal Crown',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a golden royal crown with jewels on the person like a king or queen',
    icon: '👑',
    intensity: 0.65,
  },
  {
    id: 'acc-headwear-bandana',
    name: 'Bandana',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a bandana tied around the forehead',
    icon: '🏴‍☠️',
    intensity: 0.60,
  },
  {
    id: 'acc-headwear-beret',
    name: 'Beret',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a French-style beret hat on the person, tilted to one side',
    icon: '🇫🇷',
    intensity: 0.65,
  },
  {
    id: 'acc-headwear-snapback',
    name: 'Snapback',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a snapback baseball cap on the person, worn slightly to the side',
    icon: '🧢',
    intensity: 0.65,
  },
  {
    id: 'acc-headwear-viking-helmet',
    name: 'Viking Helmet',
    category: 'accessories',
    subcategory: 'headwear',
    prompt: 'Add a Viking helmet with horns on the person',
    icon: '⚔️',
    intensity: 0.70,
  },

  // ============================================================
  // ACCESSORIES - Eyewear
  // ============================================================
  {
    id: 'acc-eyewear-aviator',
    name: 'Aviator Sunglasses',
    category: 'accessories',
    subcategory: 'eyewear',
    prompt: 'Add classic aviator sunglasses on the person',
    icon: '🕶️',
    intensity: 0.60,
  },
  {
    id: 'acc-eyewear-round-glasses',
    name: 'Round Glasses',
    category: 'accessories',
    subcategory: 'eyewear',
    prompt: 'Add round John Lennon style glasses on the person',
    icon: '👓',
    intensity: 0.55,
  },
  {
    id: 'acc-eyewear-cat-eye',
    name: 'Cat Eye Glasses',
    category: 'accessories',
    subcategory: 'eyewear',
    prompt: 'Add retro cat eye glasses on the person',
    icon: '🐱',
    intensity: 0.55,
    gender: 'female',
  },
  {
    id: 'acc-eyewear-monocle',
    name: 'Monocle',
    category: 'accessories',
    subcategory: 'eyewear',
    prompt: 'Add a distinguished monocle on one eye with a gold chain',
    icon: '🧐',
    intensity: 0.55,
  },
  {
    id: 'acc-eyewear-ski-goggles',
    name: 'Ski Goggles',
    category: 'accessories',
    subcategory: 'eyewear',
    prompt: 'Add ski goggles pushed up on the forehead',
    icon: '⛷️',
    intensity: 0.60,
  },
  {
    id: 'acc-eyewear-nerd-glasses',
    name: 'Nerd Glasses',
    category: 'accessories',
    subcategory: 'eyewear',
    prompt: 'Add oversized thick-frame nerd glasses on the person',
    icon: '🤓',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Nose (4 items) — all neutral
  // ============================================================
  {
    id: 'facial-nose-smaller',
    name: 'Smaller',
    category: 'facial',
    subcategory: 'nose',
    prompt: "Make the person's nose slightly smaller and more refined while keeping their identity",
    icon: '👃',
    intensity: 0.55,
  },
  {
    id: 'facial-nose-button',
    name: 'Button Nose',
    category: 'facial',
    subcategory: 'nose',
    prompt: 'Give the person a small, round, slightly upturned nose with a soft rounded tip while keeping everything else the same',
    icon: '🔘',
    intensity: 0.55,
  },
  {
    id: 'facial-nose-straight-bridge',
    name: 'Straight Bridge',
    category: 'facial',
    subcategory: 'nose',
    prompt: 'Give the person a straight nose bridge while keeping everything else the same',
    icon: '➖',
    intensity: 0.55,
  },
  {
    id: 'facial-nose-wider',
    name: 'Wider',
    category: 'facial',
    subcategory: 'nose',
    prompt: "Make the person's nose slightly wider while keeping everything else the same",
    icon: '↔️',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Jawline (4 items) — all neutral
  // ============================================================
  {
    id: 'facial-jawline-chiseled',
    name: 'Chiseled',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a sharper more chiseled jawline while keeping everything else the same',
    icon: '💠',
    intensity: 0.55,
  },
  {
    id: 'facial-jawline-softer',
    name: 'Softer',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a softer more rounded jawline while keeping everything else the same',
    icon: '⭕',
    intensity: 0.55,
  },
  {
    id: 'facial-jawline-square',
    name: 'Square',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a strong square jawline while keeping everything else the same',
    icon: '◾',
    intensity: 0.55,
  },
  {
    id: 'facial-jawline-v-shape',
    name: 'V-Shape',
    category: 'facial',
    subcategory: 'jawline',
    prompt: 'Give the person a V-shaped jawline while keeping everything else the same',
    icon: '✔️',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Eyes (4 items) — all neutral
  // ============================================================
  {
    id: 'facial-eyes-larger',
    name: 'Larger Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Make the person's eyes slightly larger and more prominent",
    icon: '👀',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-almond',
    name: 'Almond Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: 'Give the person more almond-shaped eyes',
    icon: '🌰',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-rounder',
    name: 'Rounder Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: 'Give the person rounder more open eyes',
    icon: '⚪',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-green',
    name: 'Green Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to vivid green",
    icon: '🟢',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-blue',
    name: 'Blue Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to bright blue",
    icon: '🔵',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-brown',
    name: 'Brown Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to warm brown",
    icon: '🟤',
    intensity: 0.55,
  },
  {
    id: 'facial-eyes-hazel',
    name: 'Hazel Eyes',
    category: 'facial',
    subcategory: 'eyes',
    prompt: "Change the person's eye color to hazel with golden-brown tones",
    icon: '🟡',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Lips (4 items) — all neutral
  // ============================================================
  {
    id: 'facial-lips-fuller',
    name: 'Fuller Lips',
    category: 'facial',
    subcategory: 'lips',
    prompt: 'Give the person fuller plumper lips while keeping everything else the same',
    icon: '👄',
    intensity: 0.55,
  },
  {
    id: 'facial-lips-thinner',
    name: 'Thinner Lips',
    category: 'facial',
    subcategory: 'lips',
    prompt: 'Give the person thinner more refined lips while keeping everything else the same',
    icon: '➖',
    intensity: 0.55,
  },
  {
    id: 'facial-lips-wider-smile',
    name: 'Wider Smile',
    category: 'facial',
    subcategory: 'lips',
    prompt: 'Give the person a wider more prominent smile',
    icon: '😁',
    intensity: 0.55,
  },
  {
    id: 'facial-lips-cupids-bow',
    name: "Cupid's Bow",
    category: 'facial',
    subcategory: 'lips',
    prompt: "Give the person more defined cupid's bow lips",
    icon: '🏹',
    intensity: 0.55,
  },

  // ============================================================
  // FACIAL - Cheekbones (3 items) — all neutral
  // ============================================================
  {
    id: 'facial-cheekbones-higher',
    name: 'Higher',
    category: 'facial',
    subcategory: 'cheekbones',
    prompt: 'Give the person higher more prominent cheekbones',
    icon: '⬆️',
    intensity: 0.55,
  },
  {
    id: 'facial-cheekbones-more-prominent',
    name: 'More Prominent',
    category: 'facial',
    subcategory: 'cheekbones',
    prompt: "Make the person's cheekbones more defined and sculpted",
    icon: '💎',
    intensity: 0.55,
  },
  {
    id: 'facial-cheekbones-softer',
    name: 'Softer',
    category: 'facial',
    subcategory: 'cheekbones',
    prompt: 'Give the person softer less prominent cheekbones for a rounder face shape',
    icon: '⭕',
    intensity: 0.55,
  },

  // ============================================================
  // BODY
  // ============================================================
  {
    id: 'body-slimmer',
    name: 'Slimmer',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear slimmer and more toned',
    icon: '🧘',
    intensity: 0.70,
  },
  {
    id: 'body-athletic',
    name: 'Athletic',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear more muscular and athletic',
    icon: '🏃',
    intensity: 0.70,
  },
  {
    id: 'body-taller',
    name: 'Taller',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear taller with longer proportions',
    icon: '⬆️',
    intensity: 0.70,
  },
  {
    id: 'body-bodybuilder',
    name: 'Body Builder',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear as a muscular bodybuilder',
    icon: '💪',
    intensity: 0.70,
  },
  {
    id: 'body-curvier',
    name: 'Curvier',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear curvier with more defined curves',
    icon: '➰',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'body-hourglass',
    name: 'Hourglass',
    category: 'body',
    subcategory: 'body',
    prompt: 'Give the person an hourglass figure with defined waist',
    icon: '⏳',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'body-petite',
    name: 'Petite',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear petite with a smaller more delicate frame',
    icon: '🌷',
    intensity: 0.70,
    gender: 'female',
  },
  {
    id: 'body-broad-shoulders',
    name: 'Broad Shoulders',
    category: 'body',
    subcategory: 'body',
    prompt: 'Give the person broader more muscular shoulders',
    icon: '🔱',
    intensity: 0.70,
    gender: 'male',
  },
  {
    id: 'body-lean-ripped',
    name: 'Lean & Ripped',
    category: 'body',
    subcategory: 'body',
    prompt: 'Make the person appear lean and ripped with visible muscle definition',
    icon: '🏋️',
    intensity: 0.70,
    gender: 'male',
  },

  // ============================================================
  // AGE-FANTASY - Age (6 items) — all neutral
  // ============================================================
  {
    id: 'age-10-younger',
    name: '10 Years Younger',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 10 years younger while preserving their identity',
    icon: '⏪',
    intensity: 0.70,
  },
  {
    id: 'age-20-younger',
    name: '20 Years Younger',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 20 years younger while preserving their identity',
    icon: '⏪',
    intensity: 0.70,
  },
  {
    id: 'age-teenage',
    name: 'Teenage',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look like a teenager while preserving their identity',
    icon: '🧒',
    intensity: 0.70,
  },
  {
    id: 'age-10-older',
    name: '10 Years Older',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 10 years older while preserving their identity',
    icon: '⏩',
    intensity: 0.70,
  },
  {
    id: 'age-20-older',
    name: '20 Years Older',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look 20 years older while preserving their identity',
    icon: '⏩',
    intensity: 0.70,
  },
  {
    id: 'age-elderly',
    name: 'Elderly',
    category: 'age-fantasy',
    subcategory: 'age',
    prompt: 'Make the person look elderly with wrinkles and gray hair while preserving their identity',
    icon: '🧓',
    intensity: 0.70,
  },

  // ============================================================
  // AGE-FANTASY - Fantasy (12 items) — all neutral
  // ============================================================
  {
    id: 'fantasy-elf',
    name: 'Elf',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a fantasy elf with pointed ears and ethereal features',
    icon: '🧝',
    intensity: 0.85,
  },
  {
    id: 'fantasy-vampire',
    name: 'Vampire',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a vampire with pale skin, fangs, and red eyes',
    icon: '🧛',
    intensity: 0.85,
  },
  {
    id: 'fantasy-zombie',
    name: 'Zombie',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a zombie with decaying skin and hollow eyes',
    icon: '🧟',
    intensity: 0.85,
  },
  {
    id: 'fantasy-alien',
    name: 'Alien',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into an alien with otherworldly features',
    icon: '👽',
    intensity: 0.85,
  },
  {
    id: 'fantasy-cyborg',
    name: 'Cyborg',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a cyborg with robotic mechanical parts on their face',
    icon: '🤖',
    intensity: 0.85,
  },
  {
    id: 'fantasy-fairy',
    name: 'Fairy',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a fairy with glowing skin and sparkly wings',
    icon: '🧚',
    intensity: 0.85,
  },
  {
    id: 'fantasy-mermaid',
    name: 'Mermaid',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a mermaid with iridescent scales and ocean-themed look',
    icon: '🧜',
    intensity: 0.85,
  },
  {
    id: 'fantasy-superhero',
    name: 'Superhero',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a superhero with a mask and cape',
    icon: '🦸',
    intensity: 0.85,
  },
  {
    id: 'fantasy-anime',
    name: 'Anime',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into an anime character with large eyes and stylized features',
    icon: '🎭',
    intensity: 0.85,
  },
  {
    id: 'fantasy-pixar',
    name: 'Pixar Character',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a Pixar 3D animated character',
    icon: '🎬',
    intensity: 0.85,
  },
  {
    id: 'fantasy-werewolf',
    name: 'Werewolf',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a werewolf with fur and sharp features',
    icon: '🐺',
    intensity: 0.85,
  },
  {
    id: 'fantasy-dragon-person',
    name: 'Dragon Person',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a dragon-human hybrid with scales and horns',
    icon: '🐉',
    intensity: 0.85,
  },
  {
    id: 'fantasy-witch',
    name: 'Witch',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a witch with dark robes, pointed hat, and magical green glow',
    icon: '🧙‍♀️',
    intensity: 0.85,
  },
  {
    id: 'fantasy-demon',
    name: 'Demon',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a demon with red skin, horns, and glowing eyes',
    icon: '😈',
    intensity: 0.85,
  },
  {
    id: 'fantasy-angel',
    name: 'Angel',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into an angel with a golden halo, glowing white wings, and ethereal radiance',
    icon: '😇',
    intensity: 0.85,
  },
  {
    id: 'fantasy-ghost',
    name: 'Ghost',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a transparent ghostly apparition with a pale blue ethereal glow',
    icon: '👻',
    intensity: 0.85,
  },
  {
    id: 'fantasy-ice-queen',
    name: 'Ice Queen',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into an ice queen with frozen crystalline skin, white hair, and frost effects',
    icon: '❄️',
    intensity: 0.85,
  },
  {
    id: 'fantasy-steampunk',
    name: 'Steampunk',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a steampunk character with brass goggles, gears, and Victorian-industrial clothing',
    icon: '⚙️',
    intensity: 0.85,
  },
  {
    id: 'fantasy-orc',
    name: 'Orc',
    category: 'age-fantasy',
    subcategory: 'fantasy',
    prompt: 'Transform the person into a fantasy orc with green skin, tusks, and battle scars',
    icon: '👹',
    intensity: 0.85,
  },

  // ============================================================
  // EXPRESSIONS - Mood
  // ============================================================
  {
    id: 'expr-big-smile',
    name: 'Big Smile',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have a big genuine happy smile showing teeth',
    icon: '😁',
    intensity: 0.55,
  },
  {
    id: 'expr-serious',
    name: 'Serious',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have a serious stoic expression with an intense gaze',
    icon: '😐',
    intensity: 0.55,
  },
  {
    id: 'expr-surprised',
    name: 'Surprised',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have a surprised expression with wide eyes and open mouth',
    icon: '😮',
    intensity: 0.55,
  },
  {
    id: 'expr-wink',
    name: 'Wink',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person wink one eye with a playful confident expression',
    icon: '😉',
    intensity: 0.55,
  },
  {
    id: 'expr-laughing',
    name: 'Laughing',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person burst out laughing with eyes squinting from joy',
    icon: '😂',
    intensity: 0.55,
  },
  {
    id: 'expr-angry',
    name: 'Angry',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have an angry fierce expression with furrowed brows and clenched jaw',
    icon: '😠',
    intensity: 0.55,
  },
  {
    id: 'expr-sad',
    name: 'Sad',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have a sad melancholy expression with downturned mouth and sorrowful eyes',
    icon: '😢',
    intensity: 0.55,
  },
  {
    id: 'expr-smirk',
    name: 'Smirk',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have a sly confident smirk with one corner of the mouth raised',
    icon: '😏',
    intensity: 0.55,
  },
  {
    id: 'expr-pensive',
    name: 'Pensive',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have a deep in thought pensive expression with a contemplative gaze',
    icon: '🤔',
    intensity: 0.55,
  },
  {
    id: 'expr-confident',
    name: 'Confident',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have a powerful confident expression with a slight smile and strong eye contact',
    icon: '😎',
    intensity: 0.55,
  },
  {
    id: 'expr-dreamy',
    name: 'Dreamy',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have a dreamy far-away look with soft unfocused eyes and a gentle smile',
    icon: '🥰',
    intensity: 0.55,
  },
  {
    id: 'expr-mysterious',
    name: 'Mysterious',
    category: 'expression',
    subcategory: 'mood',
    prompt: 'Make the person have an enigmatic mysterious expression like the Mona Lisa',
    icon: '🤫',
    intensity: 0.55,
  },

  // ============================================================
  // EXPRESSIONS - Funny
  // ============================================================
  {
    id: 'expr-duck-face',
    name: 'Duck Face',
    category: 'expression',
    subcategory: 'funny',
    prompt: 'Make the person do a duck face with puckered pushed-out lips',
    icon: '🦆',
    intensity: 0.55,
  },
  {
    id: 'expr-tongue-out',
    name: 'Tongue Out',
    category: 'expression',
    subcategory: 'funny',
    prompt: 'Make the person stick their tongue out playfully',
    icon: '😜',
    intensity: 0.55,
  },
  {
    id: 'expr-cross-eyed',
    name: 'Cross Eyed',
    category: 'expression',
    subcategory: 'funny',
    prompt: 'Make the person go cross-eyed looking at their nose with a silly expression',
    icon: '🤪',
    intensity: 0.60,
  },
  {
    id: 'expr-shocked',
    name: 'Shocked',
    category: 'expression',
    subcategory: 'funny',
    prompt: 'Make the person have a dramatically over-the-top shocked expression with jaw dropped',
    icon: '😱',
    intensity: 0.55,
  },
  {
    id: 'expr-snarl',
    name: 'Snarl',
    category: 'expression',
    subcategory: 'funny',
    prompt: 'Make the person do a rock and roll snarl showing teeth on one side like Billy Idol',
    icon: '🤟',
    intensity: 0.55,
  },
  {
    id: 'expr-kissy-face',
    name: 'Kissy Face',
    category: 'expression',
    subcategory: 'funny',
    prompt: 'Make the person blow a kiss with puckered lips and one eye closed',
    icon: '😘',
    intensity: 0.55,
  },
  {
    id: 'expr-blue-steel',
    name: 'Blue Steel',
    category: 'expression',
    subcategory: 'funny',
    prompt: 'Make the person do a Zoolander Blue Steel model pose with a dramatic intense pouty look',
    icon: '🔵',
    intensity: 0.55,
  },
  {
    id: 'expr-eyebrow-raise',
    name: 'Raised Eyebrow',
    category: 'expression',
    subcategory: 'funny',
    prompt: "Make the person raise one eyebrow with a skeptical questioning 'really?' expression",
    icon: '🤨',
    intensity: 0.55,
  },

  // ============================================================
  // LIGHTING
  // ============================================================
  {
    id: 'lighting-golden-hour',
    name: 'Golden Hour',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Change the lighting to warm golden hour sunlight bathing the person in a beautiful warm glow',
    icon: '🌅',
    intensity: 0.60,
  },
  {
    id: 'lighting-neon',
    name: 'Neon Glow',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Add colorful neon lighting on the person with pink and blue neon signs reflecting on the face',
    icon: '🔮',
    intensity: 0.65,
  },
  {
    id: 'lighting-studio',
    name: 'Studio Portrait',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Change the lighting to professional studio portrait lighting with a dark background and dramatic key light',
    icon: '📸',
    intensity: 0.65,
  },
  {
    id: 'lighting-dramatic-shadows',
    name: 'Dramatic Shadows',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Add dramatic chiaroscuro lighting with deep shadows and high contrast like a Rembrandt painting',
    icon: '🌑',
    intensity: 0.65,
  },
  {
    id: 'lighting-ring-light',
    name: 'Ring Light',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Add ring light illumination with characteristic circular catchlights in the eyes and even face lighting',
    icon: '⭕',
    intensity: 0.60,
  },
  {
    id: 'lighting-blue-hour',
    name: 'Blue Hour',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Change the lighting to cool blue hour twilight with soft blue ambient light',
    icon: '🌊',
    intensity: 0.60,
  },
  {
    id: 'lighting-candlelight',
    name: 'Candlelight',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Change the lighting to warm flickering candlelight with a soft romantic warm glow on the face',
    icon: '🕯️',
    intensity: 0.60,
  },
  {
    id: 'lighting-noir',
    name: 'Film Noir',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Change the lighting to black and white film noir style with dramatic venetian blind shadows across the face',
    icon: '🎬',
    intensity: 0.70,
  },
  {
    id: 'lighting-rainbow',
    name: 'Rainbow Light',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Add rainbow prismatic light casting colorful rainbow reflections across the face',
    icon: '🌈',
    intensity: 0.60,
  },
  {
    id: 'lighting-sunset-backlit',
    name: 'Sunset Backlit',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Light the person from behind with a beautiful sunset creating a glowing rim light silhouette effect',
    icon: '🌇',
    intensity: 0.65,
  },
  {
    id: 'lighting-spotlight',
    name: 'Spotlight',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Add a bright spotlight from above illuminating only the person against a dark background like on stage',
    icon: '🔦',
    intensity: 0.65,
  },
  {
    id: 'lighting-underwater',
    name: 'Underwater',
    category: 'lighting',
    subcategory: 'lighting',
    prompt: 'Add an underwater lighting effect with dappled blue-green light ripples across the face like being submerged in a pool',
    icon: '🫧',
    intensity: 0.65,
  },
];

// ============================================================
// Helper Functions
// ============================================================

/**
 * Get subcategories filtered by gender.
 */
export function getSubcategoriesForGender(
  category: TransformationCategory,
  gender?: Gender | null,
): TransformationSubcategory[] {
  const subs = SUBCATEGORIES[category] ?? [];
  if (!gender) return subs.filter((s) => !s.gender);
  return subs.filter((s) => !s.gender || s.gender === gender);
}

/**
 * Get all transformations for a given category, optionally filtered by gender.
 */
export function getTransformationsByCategory(
  category: TransformationCategory,
  gender?: Gender | null,
): Transformation[] {
  return TRANSFORMATIONS.filter(
    (t) => t.category === category && (!t.gender || t.gender === gender),
  );
}

/**
 * Get all transformations for a given category and subcategory, optionally filtered by gender.
 */
export function getTransformationsBySubcategory(
  category: TransformationCategory,
  subcategory: string,
  gender?: Gender | null,
): Transformation[] {
  return TRANSFORMATIONS.filter(
    (t) =>
      t.category === category &&
      t.subcategory === subcategory &&
      (!t.gender || t.gender === gender),
  );
}

/**
 * Find a single transformation by its unique id.
 */
export function getTransformationById(id: string): Transformation | undefined {
  return TRANSFORMATIONS.find((t) => t.id === id);
}
